HicServices/RDMP

Rdmp.Core.Tests/DataLoad/Engine/DatabaseManagement/EntityNaming/HICDatabaseConfigurationTests.cs, Rdmp.Core/DataLoad/Engine/DatabaseManagement/EntityNaming/HICDatabaseConfiguration.cs, Rdmp.Core/DataLoad/Engine/LoadExecution/Components/PopulateRAW.cs
Bug is around PopulateRAW checking all tables in RAW instead of only those loaded by the DLE
- New method to get all tables that should be in a load at the given stage (in HICDatabaseConfiguration)
- New test to ensure the names are correct
=> Fix for #13

CHANGELOG.md, Rdmp.UI/ExtractionUIs/ViewExtractionSqlUI.cs, Rdmp.UI/ProjectUI/ViewExtractionConfigurationSQLUI.cs, Rdmp.UI/SimpleDialogs/ConfigurePrimaryKeyCollisionResolverUI.cs, Rdmp.UI/SubComponents/ViewCohortIdentificationConfigurationUI.cs, Rdmp.UI/TestsAndSetup/ServicePropogation/RDMPControlCommonFunctionality.cs
=> Changed layout of exceptions in query builder UIs when things go wrong

CHANGELOG.md, Rdmp.Core/DataExport/Checks/SelectedDataSetsChecker.cs
Improves error messages in sds checker
=> Improved error messages in sds checker

CHANGELOG.md, Rdmp.Core/Providers/SearchablesMatchScorer.cs, Rdmp.UI/SimpleDialogs/NavigateTo/NavigateToObjectUI.cs
=> Added ability to search by ID in NavigateToObjectUI

Application/ResearchDataManagementPlatform/WindowManagement/WindowFactory.cs, CHANGELOG.md, Rdmp.UI/ExtractionUIs/FilterUIs/ExtractionFilterUI.cs, Rdmp.UI/SimpleControls/ObjectSaverButton.cs
Adds Yes/No save prompt on closing document tabs
/Fixes #77
=> Added save prompt to FormClosing on document tabs

CHANGELOG.md, Rdmp.Core/DataExport/DataExtraction/Pipeline/ExtractionPipelineUseCase.cs
=> Added Pipeline ID and Name now recorded in logs for Data Extractions

CHANGELOG.md, Rdmp.UI/Menus/FilterMenu.cs, Rdmp.UI/Menus/GoToMenuBuilder.cs
=> Added GoTo from filters to parent (Catalogue level) filters

CHANGELOG.md, Rdmp.Core/Startup/CorruptRepositoryConnectionDetailsException.cs, Rdmp.Core/Startup/UserSettingsRepositoryFinder.cs, Rdmp.UI/LocationsMenu/ChoosePlatformDatabasesUI.cs
=> Fixed bug when connection strings are corrupt in UserSettings

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md, Rdmp.UI.Tests/TestActivateItems.cs, Rdmp.UI/Collections/Providers/FavouritesProvider.cs, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandAddFavourite.cs, Rdmp.UI/Menus/RDMPContextMenuStrip.cs
=> Added Favourite/UnFavourite to right click context menus

CHANGELOG.md, Rdmp.Core/Caching/CachingHost.cs
CachingHost now logs the state of the CacheProgress being executed first thing on start
\closes #154
=> Added logging

CHANGELOG.md, Rdmp.UI/CatalogueSummary/LoadEvents/ViewInsertsAndUpdatesDialog.cs
=> Fixed using wrong Syntax for view INSERTS/UPDATES

Application/ResearchDataManagementPlatform/RDMPMainForm.cs, Application/ResearchDataManagementPlatform/WindowManagement/TopBar/RDMPTaskBarUI.cs, Application/ResearchDataManagementPlatform/WindowManagement/WindowArranging/WindowArranger.cs
=> fix for #172

CHANGELOG.md, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandChooseHICProjectDirectory.cs, Rdmp.UI/DataLoadUIs/LoadMetadataUIs/ChooseLoadFolderUI.cs
=> Fix for #171

CHANGELOG.md, Rdmp.Core.Tests/DataLoad/Engine/DatabaseManagement/TableInfoCloneOperationTests.cs, Rdmp.Core/Providers/ProblemProvider.cs, Rdmp.UI/Rules/BinderWithErrorProviderFactory.cs, Rdmp.UI/Rules/NoBadNamesRule.cs
=> Fix for #187

CHANGELOG.md, Rdmp.Core/CommandLine/DatabaseCreation/PatchDatabaseOptions.cs, Rdmp.Core/CommandLine/DatabaseCreation/PlatformDatabaseCreationOptions.cs, Rdmp.Core/CommandLine/Options/PatchDatabaseOptions.cs, Rdmp.UI/Versioning/PatchingUI.cs, Reusable/MapsDirectlyToDatabaseTable/Versioning/MasterDatabaseScriptExecutor.cs, Tools/rdmp/Program.cs
- Moved patch to run logic out of `PatchingUI` into `MasterDatabaseScriptExecutor`
=> Added patch command to update database schemas from CLI

README.md
- Update README.md with post-Travis status badge (fixes #204)
=> Update README.md with post-Travis status badge

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.UI/Menus/RDMPContextMenuStrip.cs
=> Fix for #215

CHANGELOG.md, Rdmp.Core.Tests/Curation/Integration/LookupTest.cs, Rdmp.Core/Providers/CatalogueChildProvider.cs, Rdmp.Core/Providers/Nodes/CatalogueLookupUsageNode.cs
=> Better fix for #214

CHANGELOG.md, Rdmp.Core.Tests/CommandExecution/TestExecuteCommandSetUserSetting.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandListUserSettings.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSetUserSetting.cs
=> Added commands to view/edit user settings from CLI

CHANGELOG.md, Rdmp.Core.Tests/DataExport/DataExtraction/SimpleFileExtractorTests.cs, Rdmp.Core/DataExport/DataExtraction/Pipeline/FileExtractor.cs, Rdmp.Core/DataExport/DataExtraction/Pipeline/SimpleFileExtractor.cs, Rdmp.UI/ProjectUI/ExecuteExtractionUI.cs
=> Added SimpleFileExtractor component

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewClassBasedProcessTask.cs, Rdmp.UI/Menus/LoadStageNodeMenu.cs
=> Added ProcessTask creation menu items to load stage nodes in console GUI

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs
\fixes #234 
Adds a 'Set' command to the directory node under load metadatas in CLI
=> \fixes #234

CHANGELOG.md, Tools/rdmp/CommandLine/Gui/ConsoleGuiSqlEditor.cs
=> Added timeout control to ConsoleGuiSqlEditor

CHANGELOG.md, Tools/rdmp/CommandLine/Gui/ConsoleGuiSqlEditor.cs
=> Added ability to save results of CLI Sql Editor (table) to CSV

CHANGELOG.md, Rdmp.Core/OrderableComparer.cs, Rdmp.UI/Collections/RDMPCollectionCommonFunctionalityTreeHijacker.cs, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs
=> Fix for #263 CLI Gui branch ordering

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddAggregateConfigurationToCohortIdentificationSetContainer.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddCatalogueToCohortIdentificationSetContainer.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewCohortIdentificationConfiguration.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandImportCohortIdentificationConfiguration.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSetContainerOperation.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecutecommandAddCohortSubContainer.cs, Rdmp.Core/CommandExecution/BasicCommandExecution.cs, Rdmp.Core/Providers/CatalogueProblemProvider.cs, Rdmp.UI/Menus/CohortAggregateContainerMenu.cs
Moves cohort builder commands out of UI code and into main command execution framework.
/fixes #275 
/fixes #262
=> Cic improvements

CHANGELOG.md, Rdmp.Core/CommandLine/Runners/CacheRunner.cs, Rdmp.Core/Curation/Data/Cache/CacheProgress.cs, Rdmp.Core/Curation/Data/Cache/ICacheProgress.cs
=> Made CacheProgress ILoggedActivityRootObject

CHANGELOG.md, Rdmp.Core/Providers/Nodes/CatalogueItemsNode.cs, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs
=> Added AspectGetter for console gui

CHANGELOG.md, Rdmp.Core.Tests/CommandExecution/TestExecuteCommandImportFilterContainerTree.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandImportFilterContainerTree.cs
=> Fix import container op

CHANGELOG.md, Rdmp.UI/ScintillaHelper/ScintillaMenu.cs, Rdmp.UI/ScintillaHelper/ScintillaTextEditorFactory.cs
Throttles spell checking to once every 10 seconds
Done on Leave and on demand (F7 / context menu item).
/fixes  #282
=> Throttled spellchecking

CHANGELOG.md, Rdmp.UI/ChartLookAndFeelSetter.cs
=> Fixed DQE graph when data has dates before the year 1,000

.github/workflows/build.yml
=> Make Linux builds self-contained too

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandExecuteAggregateGraph.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.Core/CommandExecution/BasicCommandExecution.cs, Rdmp.Core/CommandExecution/IBasicActivateItems.cs, Rdmp.Core/CommandLine/Interactive/ConsoleInputManager.cs, Rdmp.Core/Curation/Data/Aggregation/AggregateDimension.cs, Rdmp.Core/DataViewing/ViewAggregateExtractUICollection.cs, Rdmp.Core/Providers/CatalogueChildProvider.cs, Rdmp.UI.Tests/TestActivateItems.cs, Rdmp.UI/AggregationUIs/Advanced/SelectColumnUI.cs, Rdmp.UI/CommandExecution/AtomicCommands/BasicUICommandExecution.cs, Rdmp.UI/Menus/AggregateConfigurationMenu.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiSqlEditor.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiViewGraph.cs, Tools/rdmp/CommandLine/Gui/Windows/GraphView.cs
Moves ExecuteGraph functions out of UI code and into Core.  Each `IActivateItems` can implement differently.
GraphView code is same as in my PR here:
https://github.com/migueldeicaza/gui.cs/pull/1201
Console:
Windows:
=> Cli graphs

CHANGELOG.md, Rdmp.Core/Providers/CatalogueChildProvider.cs, Rdmp.UI/Collections/SessionCollectionUI.cs
=> Fixed adding Pipeline objects to Sessions not working

CHANGELOG.md, Rdmp.Core.Tests/CommandExecution/ExecuteCommandAlterTableMakeDistinctTests.cs, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/Alter/ExecuteCommandAlterTableMakeDistinct.cs
=> Added new command 'alter table make distinct'

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs
=> Tidied up cic container context menu

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewCohortStore.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandPrunePlugin.cs, Rdmp.Core/CommandExecution/BasicCommandExecution.cs, Rdmp.Core/CommandLine/DatabaseCreation/ExampleDatasetsCreation.cs, Rdmp.Core/CommandLine/Options/PackOptions.cs, Rdmp.Core/CommandLine/Runners/PackPluginRunner.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiRunPipeline.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiServerDatabaseTableSelector.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiSqlEditor.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiViewLogs.cs, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs, releases.xml
/fixes #351
/fixes #350
/fixes #349
/fixes #345
/fixes #353
/fixes #352
=> Console fixes

CHANGELOG.md, Rdmp.Core/Providers/CatalogueChildProvider.cs
=> Fixed arguments not showing up under components of OtherPipelinesNode

CHANGELOG.md, Rdmp.Core.Tests/Reports/CustomMetadataReportTests.cs, Rdmp.Core/Reports/CustomMetadataReport.cs
=> Added more DQE date parameters to custom metadata reports

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.UI/Menus/ColumnInfoMenu.cs, Tools/rdmp/CommandLine/Gui/Windows/RunnerWindows/RunEngineWindow.cs
Fixes #368
Fixes #375
Fixes #372
=> RunEngineWindow fixes

CHANGELOG.md, Rdmp.Core/CohortCreation/Execution/CohortCompiler.cs
=> Added crash message to commit cic

.github/workflows/build.yml, CHANGELOG.md, Rdmp.Core.Tests/Reports/CustomMetadataReportTests.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandExtractMetadata.cs, Rdmp.Core/DataQualityEngine/Data/ColumnState.cs, Rdmp.Core/DataQualityEngine/Data/Evaluation.cs, Rdmp.Core/Reports/CustomMetadataReport.cs, Rdmp.Core/Repositories/DQERepository.cs
Adds more DQE options to `ExtractMetadata` (with custom template) command
=> More dqe options

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandExecuteAggregateGraph.cs, Rdmp.Core/CommandLine/Interactive/ConsoleInputManager.cs
=> Added to file option for ExecuteCommandExecuteAggregateGraph

CHANGELOG.md, Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiViewLogs.cs
=> Added TopX and Filter (text) to console view logs

CHANGELOG.md, Rdmp.UI/ChecksUI/ChecksUI.cs, Rdmp.UI/ChecksUI/PopupChecksUI.cs, Rdmp.UI/ChecksUI/RAGSmiley.cs, Rdmp.UI/ChecksUI/RAGSmileyToolStrip.cs, Rdmp.UI/ExceptionCounterUI.cs, Rdmp.UI/TestsAndSetup/ServicePropogation/RDMPControlCommonFunctionality.cs, Rdmp.UI/Versioning/PatchingUI.cs
/fixes #396 
Reduces calls to InvokeRequired which doesn't seem as reliable in dotnet5 as framework and solves performance issues in ChecksUI
=> Checks UI bugfixes

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/CatalogueCreationCommands/ExecuteCommandCreateNewCatalogueByImportingExistingDataTable.cs
=> Import existing table now prompts to delete TableInfo when cancelled

.github/workflows/build.yml
=> Adjust Choco syntax for SQL Server as workaround for reboot issue

CHANGELOG.md, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueArrayUI.cs, Rdmp.UI/SimpleDialogs/SelectIMapsDirectlyToDatabaseTableDialog.cs
=> Preserve original selection in ArgumentValueArrayUI 'Pick' popup

CHANGELOG.md, Rdmp.Core.Tests/Validation/Constraints/Secondary/PredictionNotNullTest.cs, Rdmp.Core/DataQualityEngine/Reports/CatalogueConstraintReport.cs, Rdmp.Core/Validation/Constraints/Secondary/Predictor/Prediction.cs
=> Fixed Lookup DQE rule

CHANGELOG.md, Rdmp.Core/DataQualityEngine/Data/PeriodicityState.cs
=> Fixed ambigious column order in GetPeriodicityForDataTableForEvaluation

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.UI/Collections/RDMPCollectionCommonFunctionality.cs, Rdmp.UI/Menus/RDMPContextMenuStrip.cs, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs
=> Support for delete/disable multiple in console gui

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSet.cs, Tools/rdmp/CommandLine/Gui/Windows/ConsoleGuiEdit.cs
_New behaviour, command is impossible so error appears before prompting for new value_
Fixes #452
=> Set command now impossible for ID property

Rdmp.UI/SimpleDialogs/SimpleFileImporting/CreateNewCatalogueByImportingFileUI.Designer.cs
=> Changed checkbox to use docking

Rdmp.Core.Tests/DataExport/DataAccess/SelectedColumnsTests.cs, Rdmp.Core/CohortCreation/Execution/AggregationTask.cs, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandExportLoggedDataToCsv.cs, Rdmp.Core/Curation/Data/DataLoad/ANOTable.cs, Rdmp.Core/Curation/Data/LoadModuleAssembly.cs, Rdmp.Core/Curation/Data/Serialization/DictionaryAsArrayResolver.cs, Rdmp.Core/Curation/Data/WindowLayout.cs, Rdmp.Core/DataLoad/Modules/Mutilators/Dilution/Operations/ExcludeRight3OfUKPostcodes.cs, Rdmp.Core/DataLoad/Modules/Mutilators/Dilution/Operations/RoundDateToMiddleOfQuarter.cs, Rdmp.Core/DataLoad/Triggers/DiffDatabaseDataFetcher.cs, Rdmp.Core/DataQualityEngine/Data/PeriodicityState.cs, Rdmp.Core/DataQualityEngine/Reports/LoadProgressSummaryReport.cs, Rdmp.Core/Repositories/DQERepository.cs, Rdmp.Core/Repositories/RowVerCache.cs, Rdmp.UI.Tests/CohortUI/CohortSourceManagement/ExternalCohortTableUITests.cs, Rdmp.UI.Tests/DataLoadUIs/ANOUIs/ANOTableManagement/ColumnInfoToANOTableConverterUITests.cs, Rdmp.UI.Tests/DataRelease/DataReleaseUITests.cs, Rdmp.UI.Tests/DesignPatternTests/ClassFileEvaluation/DocumentationCrossExaminationTest.cs, Rdmp.UI.Tests/DesignPatternTests/MarkdownCodeBlockTests.cs, Rdmp.UI.Tests/ExtractionUIs/JoinsAndLookups/LookupBrowserUITests.cs, Rdmp.UI.Tests/LogViewer/LoggingTabUITests.cs, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs, Tools/rdmp/Program.cs
=> Fixed mixed use of tab and space for indentation (space only now)

CHANGELOG.md, Rdmp.Core/Databases/DataExportDatabase/up/023_ExtractableColumnMaxSize.sql, Rdmp.Core/Rdmp.Core.csproj
=> Removed limit of 500 characters on extraction SQL of columns

Application/ResearchDataManagementPlatform/ResearchDataManagementPlatform.csproj, CHANGELOG.md, Plugins/Plugin.Test/Plugin.Test.csproj, Plugins/Plugin.UI/Plugin.UI.csproj, Plugins/Plugin/Plugin.csproj, Rdmp.Core.Tests/DataLoad/Engine/Integration/PipelineTests/Components/ColumnSwapperTests.cs, Rdmp.Core.Tests/Rdmp.Core.Tests.csproj, Rdmp.Core/DataLoad/Modules/DataFlowOperations/Swapping/ColumnSwapper.cs, Rdmp.Core/Rdmp.Core.csproj, Rdmp.UI.Tests/Rdmp.UI.Tests.csproj, Rdmp.UI/Rdmp.UI.csproj, Reusable/MapsDirectlyToDatabaseTable/MapsDirectlyToDatabaseTable.csproj, Reusable/ReusableLibraryCode/ReusableLibraryCode.csproj, Reusable/Tests/ReusableCodeTests/ReusableCodeTests.csproj, Tests.Common/Tests.Common.csproj, Tools/rdmp/rdmp.csproj
=> Added Input and Output col name options to ColumnSwapper

CHANGELOG.md, Documentation/CodeTutorials/Packages.md, Plugins/Plugin.UI/Plugin.UI.nuspec, Rdmp.UI/Rdmp.UI.csproj
=> Change to targetting HIC.System.Windows.Forms.DataVisualization

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandScriptTables.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.Core/CommandLine/Interactive/Picking/CommandLineObjectPickerArgumentValue.cs, Rdmp.Core/DataViewing/ArbitraryTableExtractionUICollection.cs
Adds new command ScriptTables
Fixes #469
```
PS Z:\Repos\RDMP\Tools\rdmp\bin\Debug\net5.0> ./rdmp cmd DescribeCommand ScriptTables
Description:
Script multiple tables optionally porting schema to a new server/DBMS type
USAGE:
./rdmp.exe cmd ScriptTables <tableInfos> <dbType> <dbName> <outFile>
PARAMETERS:
tableInfos TableInfo[]         Tables to script
dbType     Nullable`1          Optional alternate DBMS Type to port the schema to
dbName     String              Optional alternate database name to use in the script generated.
outFile    FileInfo            Optional file to write the resulting script out to.  Pass Null to output to console.
```
Script all tables in all databases known about by RDMP to MySql syntax
```
PS Z:\Repos\RDMP\Tools\rdmp\bin\Debug\net5.0> ./rdmp cmd ScriptTables …
```
=> Added ScriptTables command

CHANGELOG.md, Rdmp.Core.Tests/Reports/CustomMetadataReportTests.cs, Rdmp.Core/DataQualityEngine/Data/PeriodicityState.cs, Rdmp.Core/DataQualityEngine/DatasetTimespanCalculator.cs, Rdmp.Core/Reports/CustomMetadataReport.cs, Rdmp.Core/Reports/GovernanceReport.cs, Rdmp.Core/Reports/IDetermineDatasetTimespan.cs, Rdmp.Core/Reports/MetadataReport.cs, Rdmp.UI/Raceway/DatasetRaceway.cs
=> added discard outliers support to DatasetRaceway

README.md, Rdmp.UI.Tests/DesignPatternTests/ClassFileEvaluation/DocumentationCrossExaminationTest.cs
=> Updated build instructions

CHANGELOG.md, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandAddNewLookupTableRelationship.cs, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs
=> Fixed Catalogue context menus when IsAPI

CHANGELOG.md, Rdmp.Core/Curation/Data/Catalogue.cs
=> Made CatalogueFolder a UsefulProperty

CHANGELOG.md, Rdmp.Core/Providers/Nodes/ExtractionArbitraryFolderNode.cs, Rdmp.UI.Tests/DesignPatternTests/UserInterfaceStandardisationChecker.cs, Rdmp.UI/CommandExecution/Proposals/ProposeExecutionWhenTargetIsExtractionArbitraryFolderNode.cs, Rdmp.UI/ProjectUI/ExecuteExtractionUI.cs
Fixes #507 
_Dragging the Catalogue 'Hospital Admissions' over the top of the folder 'Core'_
=> Added ability to drop stuff into the UI folders in ExecuteExtractionUI

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md, Rdmp.Core.Tests/CommandExecution/CommandCliTests.cs, Rdmp.Core.Tests/CommandExecution/ExecuteCommandDeleteTestsCli.cs, Rdmp.Core.Tests/CommandExecution/TestExecuteCommandDescribeCommand.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandDelete.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandDescribeCommand.cs, Rdmp.Core/CommandExecution/CommandInvoker.cs, Rdmp.Core/CommandLine/Interactive/Picking/CommandLineObjectPickerArgumentValue.cs, Rdmp.Core/CommandLine/Runners/ExecuteCommandRunner.cs, Rdmp.Core/DataExport/Data/IExtractionConfiguration.cs, Rdmp.UI.Tests/CommandExecution/ExecuteCommandDeleteTests.cs, Rdmp.UI/ExtractionUIs/FilterUIs/ParameterUIs/Parameters.cd
=> Added support for deleting many objects at once from CLI

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewExtractableDataSetPackage.cs, Rdmp.Core/Curation/Data/ICatalogue.cs, Rdmp.Core/DataExport/Checks/SelectedDataSetsChecker.cs
=> Added extraction check for IsInternalDataset

CHANGELOG.md, Tools/rdmp/CommandLine/Gui/ConsoleGuiRunPipeline.cs
=> Fixed Yes/No dialog being run on wrong thread in ConsoleGuiRunPipeline

Tools/rdmp/CommandLine/Gui/ConsoleGuiSqlEditor.cs
=> Fix replacing tab with dots instead of spaces

CHANGELOG.md, Rdmp.Core.Tests/Curation/Integration/ExtractionFilterParameterSetTests.cs, Rdmp.Core/Curation/Data/ExtractionFilterParameterSet.cs
=> Fixed deleting ExtractionFilterParameterSet

CHANGELOG.md, Rdmp.Core.Tests/Databases/MasterDatabaseScriptExecutorTests.cs, Reusable/MapsDirectlyToDatabaseTable/Versioning/MasterDatabaseScriptExecutor.cs
=> Improved error message when double creating a platform db

CHANGELOG.md, Rdmp.UI/ExtractionUIs/ExtractionInformationUI.cs
=> Fixed bug saving extraction transforms with no alias

CHANGELOG.md, Rdmp.UI/TestsAndSetup/ServicePropogation/RDMPControlCommonFunctionality.cs
=> Checks toolbar

Application/ResearchDataManagementPlatform/WindowManagement/TopBar/RDMPTaskBarUI.cs, CHANGELOG.md
=> Shorter task bar tooltips

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandBulkImportTableInfos.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.Core/CommandExecution/IBasicActivateItems.cs, Rdmp.Core/CommandLine/Interactive/ConsoleInputManager.cs, Rdmp.UI.Tests/TestActivateItems.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs, Tools/rdmp/CommandLine/Gui/Windows/ConsoleGuiSelectMany.cs
Fixes #519 
Space to select, Enter to finalise selection.  If no objects are marked with Space and Enter is pressed then the selected item is chosen.
=> Bulk import pick

Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs
=> fixed GetDialogDimensions when Frame is null

CHANGELOG.md, Rdmp.Core/Curation/Data/EncryptedPasswordHost.cs
=> Fix not implemented exception with username/password auth in ViewSql

CHANGELOG.md, Documentation/CodeTutorials/DoubleClickAndDragDrop.md, Documentation/CodeTutorials/Glossary.md, Rdmp.Core.Tests/CommandExecution/ExecuteCommandConfirmLogsTests.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandConfirmLogs.cs
Fixes #632
Only a test to expose the issue for now
=> Make ConfirmLogs work with multiple CacheProgress

CHANGELOG.md, Rdmp.Core/Providers/SearchablesMatchScorer.cs, Rdmp.UI/Collections/CatalogueCollectionUI.Designer.cs, Rdmp.UI/Collections/Providers/IDColumnProvider.cs
=> Pipeline id 0

Rdmp.Core/Providers/SearchablesMatchScorer.cs, Rdmp.UI/Collections/CatalogueCollectionFilterUI.cs, Rdmp.UI/Collections/CatalogueCollectionUI.cs, Rdmp.UI/SimpleDialogs/NavigateTo/NavigateToObjectUI.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.resx, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
Update to find filters to sync and a performance fix
=> Refine Find Catalogue filter flags (e.g. IsDeprecated etc)

Application/ResearchDataManagementPlatform/Menus/RDMPTopMenuStripUI.Designer.cs, Application/ResearchDataManagementPlatform/Menus/RDMPTopMenuStripUI.cs, Application/ResearchDataManagementPlatform/Menus/RDMPTopMenuStripUI.resx, CHANGELOG.md
=> Added 'restart application' menu item

Rdmp.Core/CommandExecution/GoToCommandFactory.cs
=> Added GoTo Project from Catalogue

CHANGELOG.md, Rdmp.Core/DataExport/Checks/SelectedDataSetsChecker.cs, Rdmp.Core/DataExport/DataExtraction/Pipeline/Destinations/ExecuteFullExtractionToDatabaseMSSql.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Reusable/ReusableLibraryCode/Checks/CheckEventArgs.cs, Reusable/ReusableLibraryCode/Checks/ErrorCode.cs, Reusable/ReusableLibraryCode/Checks/ErrorCodes.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Add error codes and fix Extract to Database Checks

Application/ResearchDataManagementPlatform/WindowManagement/TopBar/RDMPTaskBarUI.Designer.cs, Application/ResearchDataManagementPlatform/WindowManagement/TopBar/RDMPTaskBarUI.cs, Application/ResearchDataManagementPlatform/WindowManagement/WindowManager.cs, Rdmp.UI/Collections/DataExportCollectionUI.Designer.cs
=> Updated "Data Export" tab and tooltip to be "Projects"

CHANGELOG.md, Rdmp.Core.Tests/Curation/Unit/AggregateConfigurationTests.cs, Rdmp.Core/Curation/Data/Aggregation/AggregateConfiguration.cs, Rdmp.UI/AggregationUIs/AggregateGraphUI.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiViewGraph.cs
=> Added IncludeZeroSeriesInGraphs user setting

CHANGELOG.md, Rdmp.UI/AggregationUIs/AggregateGraphUI.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiViewGraph.cs
=> Added AggregateConfiguration name as chart titles

CHANGELOG.md, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandCollapseChildNodes.cs, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandExpandAllNodes.cs
=> Enabled Expand/Collapse all when right clicking whitespace

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, Rdmp.Core/DataExport/Data/ExtractionConfiguration.cs, Rdmp.UI/CatalogueSummary/LoadEvents/LoadEventsTreeView.cs, Rdmp.UI/Collections/SessionCollectionUI.cs, Rdmp.UI/DataViewing/ViewSQLAndResultsWithDataGridUI.cs, Rdmp.UI/Overview/DataLoadsGraph.cs, Rdmp.UI/PieCharts/GoodBadCataloguePieChart.cs, Rdmp.UI/ProjectUI/Datasets/ConfigureDatasetUI.cs, Rdmp.UI/ProjectUI/ExecuteExtractionUI.cs, Rdmp.UI/ProjectUI/ExtractionConfigurationUI.cs, Rdmp.UI/Raceway/DatasetRaceway.cs, Rdmp.UI/TestsAndSetup/ServicePropogation/INamedTab.cs, Rdmp.UI/TestsAndSetup/ServicePropogation/RDMPSingleDatabaseObjectControl.cs
Ticket #621 contains decision making process. Trying to make tab titles short and quick to use but also include extra detail in the tooltip to help explain.
Fixes #621
=> Updated Extraction configuration tab titles and added custom tooltips

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandGenerateReleaseDocument.cs, Rdmp.Core/CommandExecution/Combining/ExtractableCohortCombineable.cs, Rdmp.Core/DataExport/Data/ExtractableCohort.cs
=> Fixed UI interactions where a cohort is unreachable to complete faster

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/CohortCreationCommands/CohortCreationCommandExecution.cs, Rdmp.Core/CommandExecution/AtomicCommands/CohortCreationCommands/ExecuteCommandCreateNewCohortByExecutingACohortIdentificationConfiguration.cs
=> Fixed `CohortCreationCommandExecution` persisting user selections

Rdmp.Core.Tests/Providers/CatalogueProblemProviderTests.cs, Rdmp.Core/Providers/CatalogueProblemProvider.cs
Fixes #681 
Bigger discussion required around default Cohort builder options
=> Cohort builder root warnings

Rdmp.UI/PipelineUIs/DataObjects/DataFlowComponentVisualisation.Designer.cs, Rdmp.UI/PipelineUIs/DataObjects/DataFlowComponentVisualisation.cs, Rdmp.UI/PipelineUIs/DataObjects/DataFlowComponentVisualisation.resx, Rdmp.UI/PipelineUIs/DataObjects/PipelineComponentVisualisation.cs, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentCollectionUI.Designer.cs, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentCollectionUI.cs, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentCollectionUI.resx, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueArrayUI.Designer.cs, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueComboBoxUI.Designer.cs, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueTextUI.Designer.cs, Rdmp.UI/PipelineUIs/Pipelines/Models/DividerLineControl.Designer.cs, Rdmp.UI/PipelineUIs/Pipelines/Models/DividerLineControl.resx, Rdmp.UI/PipelineUIs/Pipelines/PipelineDiagramUI.cs, Rdmp.UI/PipelineUIs/Pipelines/PipelineWorkAreaUI.Designer.cs
=> Configure pipeline visual updates

CHANGELOG.md, Documentation/CodeTutorials/Packages.md, Plugins/Plugin.Test/Plugin.Test.nuspec, Plugins/Plugin.UI/Plugin.UI.nuspec, Plugins/Plugin/Plugin.nuspec, Rdmp.Core/Curation/Data/SafeDirectoryCatalog.cs, Reusable/ReusableLibraryCode/ReusableLibraryCode.csproj, Tests.Common/UnitTests.cs
=> Bad assembly loading

Reusable/ReusableLibraryCode/UsefulStuff.cs, Reusable/Tests/ReusableCodeTests/UsefulStuffTests.cs
Now works correctly if string ends of starts with ALLCapsLETTERS
Fixes #752
=> Updated PascalCaseStringToHumanReadable function

Rdmp.UI.Tests/TypeTextOrCancelDialogTests.cs, Rdmp.UI/SimpleDialogs/TypeTextOrCancelDialog.Designer.cs, Rdmp.UI/SimpleDialogs/TypeTextOrCancelDialog.cs, Rdmp.UI/SimpleDialogs/WideMessageBox.Designer.cs, Rdmp.UI/SubComponents/CohortIdentificationConfigurationUI.Designer.cs, Rdmp.UI/SubComponents/CohortIdentificationConfigurationUI.cs
Added scrollbars to description and editing textbox as well increasing the size of the editing text box.
Fixed #755
=> Fix cic description

Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.resx, Reusable/ReusableLibraryCode/Settings/UserSettings.cs, Reusable/ReusableLibraryCode/UsefulStuff.cs
Starting changes to address issues raised in ticket #760
=> Update layout/design/help for UserSettingsUI

Rdmp.UI/SubComponents/CohortIdentificationConfigurationUI.Designer.cs
Splitter is no longer fixed and description correctly resizes when splitter is moved. Closes issue #767
=> Splitter is no longer fixed 

Rdmp.UI/MainFormUITabs/CatalogueUI.Designer.cs, Rdmp.UI/MainFormUITabs/CatalogueUI.cs
Addresses the direct issue from #758 by updating the layout to a more sustainable format with TableLayoutPanel
=> Update catalogue UI

Rdmp.Core/DataLoad/Modules/DataFlowOperations/Swapping/ColumnSwapper.cs
Added space in help text to increase legability
Added "WHERE" to WHERELogic attribute via ContextText property
=> Updated ColumnSwapper WHERELogic property description and ContextText

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandUnMergeCohortIdentificationConfiguration.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.Core/CommandExecution/IBasicActivateItems.cs
=> Added `Confirm` to `IBasicActivateItems` and used for UnMerge

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddCatalogueToCohortIdentificationSetContainer.cs, Rdmp.Core/CommandExecution/AtomicCommands/IAtomicCommand.cs, Rdmp.Core/CommandExecution/BasicCommandExecution.cs, Rdmp.UI/Collections/RDMPCollectionCommonFunctionality.cs, Rdmp.UI/Collections/ToolStripItemComparer.cs, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs
=> Add Weight property to commands

CHANGELOG.md, Rdmp.UI/SimpleDialogs/ForwardEngineering/ConfigureCatalogueExtractabilityUI.Designer.cs, Rdmp.UI/SimpleDialogs/ForwardEngineering/ConfigureCatalogueExtractabilityUI.cs
=> Added hash on release column to ConfigureCatalogueExtractabilityUI

Application/ResearchDataManagementPlatform/Menus/RDMPTopMenuStripUI.cs
=> Made restart confirm when user setting ConfirmApplicationExiting is set

CHANGELOG.md, Rdmp.UI/ProjectUI/Datasets/ConfigureDatasetUI.cs
=> Fixed ConfigureDatasetUI not showing all available tables

Reusable/ReusableLibraryCode/UsefulStuff.cs, Reusable/Tests/ReusableCodeTests/UsefulStuffTests.cs
=> Updated PascalCaseStringToHumanReadable to remove underscores

CHANGELOG.md, Rdmp.Core/Curation/Data/Catalogue.cs, Reusable/ReusableLibraryCode/ObjectExtensions.cs
=> Added Extraction Primary Keys to Catalogue tooltip

CHANGELOG.md, Rdmp.Core/QueryBuilding/CohortQueryBuilderDependency.cs
=> Joinable cache invalidation

CHANGELOG.md, Rdmp.UI/Menus/CatalogueMenu.cs
=> Added open load dir to Catalogue context menu

Rdmp.Core.Tests/IHasSummaryTests.cs, Rdmp.Core/Curation/Data/DatabaseEntity.cs, Rdmp.Core/Curation/Data/ExtractionFilter.cs
=> Updated FilterContainer_ID to return ID

Rdmp.UI/Collections/LoadMetadataCollectionUI.cs
=> Created common BuildCommandList function to create menu options

Rdmp.Core/Autocomplete/AutoCompleteProvider.cs, Rdmp.UI/AggregationUIs/Advanced/AggregateEditorUI.cs, Rdmp.UI/AutoComplete/AutoCompleteProviderWin.cs, Rdmp.UI/CohortUI/ExtractableCohortUI.cs, Rdmp.UI/DataViewing/ViewSQLAndResultsWithDataGridUI.cs, Rdmp.UI/ExtractionUIs/ExtractionInformationUI.cs, Rdmp.UI/ExtractionUIs/FilterUIs/ExtractionFilterUI.cs, Rdmp.UI/MainFormUITabs/CatalogueItemUI.cs, Rdmp.UI/MainFormUITabs/CatalogueUI.cs, Rdmp.UI/PluginManagement/CodeGeneration/GenerateClassCodeFromTableUI.cs, Rdmp.UI/ScintillaHelper/ScintillaTextEditorFactory.cs, Rdmp.UI/SimpleDialogs/Revertable/RevertablePropertyDifferenceUI.cs, Rdmp.UI/SimpleDialogs/SqlDialogs/SQLBeforeAndAfterViewer.cs, Rdmp.UI/SimpleDialogs/ViewSourceCodeDialog.cs
=> Autocomplete Scintilla overhaul

Rdmp.UI/MainFormUITabs/CatalogueItemUI.Designer.cs, Rdmp.UI/MainFormUITabs/CatalogueUI.Designer.cs
=> Catalogueui splitter error

Rdmp.UI/Menus/FilterMenu.cs
=> Fixed enable/disable appearing twice in filter context menu

CHANGELOG.md, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandOpenExtractionDirectory.cs, Rdmp.UI/Menus/ExtractionConfigurationMenu.cs
=> Open ec dir

CHANGELOG.md, Rdmp.UI/ProjectUI/ProjectUI.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiTextDialog.cs
=> Gui fix task desc

CHANGELOG.md, Rdmp.UI/ProjectUI/ProjectUI.cs
=> Fix ProjectUI when there are unreachable cohorts

Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandOpenExtractionDirectory.cs
=> Added wording to separate "null" destination type from non flatfile

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandViewCohortSample.cs, Rdmp.Core/DataViewing/ViewCohortExtractionUICollection.cs
=> Added Save To Disk to ExtractableCohort context menu

CHANGELOG.md, Rdmp.Core/Curation/Data/Pipelines/AdvertisedPipelineComponentTypeUnderContext.cs, Rdmp.Core/Curation/Data/Pipelines/IPipelineUseCase.cs, Rdmp.Core/Curation/Data/Pipelines/PipelineComponent.cs, Rdmp.Core/Curation/Data/Pipelines/PipelineComponentRole.cs, Rdmp.Core/Curation/Data/Pipelines/PipelineUseCase.cs, Rdmp.UI/PipelineUIs/DataObjects/DataFlowComponentVisualisation.cs, Rdmp.UI/PipelineUIs/DataObjects/PipelineComponentVisualisation.cs, Rdmp.UI/PipelineUIs/Pipelines/PipelineDiagramUI.cs, Rdmp.UI/PipelineUIs/Pipelines/PipelineSelectionUI.cs
=> Strict pipeline compatibility

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/CohortCreationCommands/ExecuteCommandCreateNewCohortByExecutingACohortIdentificationConfiguration.cs
=> Added auto select for project if CIC is associated with a single project already

CHANGELOG.md, Rdmp.Core.Tests/CohortCreation/AggregateFilterPublishingTests.cs, Rdmp.Core/Curation/Data/ExtractionFilterParameter.cs
=> Remove publish filter comment check

CHANGELOG.md, Rdmp.UI/Menus/RDMPContextMenuStrip.cs
=> Fixed `SuggestedCategory` on plugin commands not working

CHANGELOG.md, Rdmp.UI/Validation/SecondaryConstraintUI.cs
=> Layout fix in SecondaryconstraintUI

CHANGELOG.md, Rdmp.Core.Tests/DataExport/Data/ExtractionProgressTests.cs, Rdmp.Core/DataExport/Data/ExtractionProgress.cs, Rdmp.Core/DataExport/Data/IExtractionProgress.cs, Rdmp.Core/DataExport/Data/RetryStrategy.cs, Rdmp.Core/DataExport/DataExtraction/Pipeline/ExtractionPipelineUseCase.cs, Rdmp.Core/Databases/DataExportDatabase/up/025_AddExtractionProgressRetry.sql, Rdmp.Core/Rdmp.Core.csproj, Rdmp.UI/MainFormUITabs/ExtractionProgressUI.Designer.cs, Rdmp.UI/MainFormUITabs/ExtractionProgressUI.cs
=> Batch retry

CHANGELOG.md, Documentation/CodeTutorials/Packages.md, Plugins/Plugin.Test/Plugin.Test.nuspec, Plugins/Plugin.UI/Plugin.UI.nuspec, Plugins/Plugin/Plugin.nuspec, Rdmp.Core/CommandLine/DatabaseCreation/PlatformDatabaseCreation.cs, Rdmp.Core/CommandLine/DatabaseCreation/PlatformDatabaseCreationOptions.cs, Rdmp.UI/LocationsMenu/ChoosePlatformDatabasesUI.Designer.cs, Rdmp.UI/LocationsMenu/ChoosePlatformDatabasesUI.cs, Reusable/MapsDirectlyToDatabaseTable/Versioning/MasterDatabaseScriptExecutor.cs, Reusable/ReusableLibraryCode/ReusableLibraryCode.csproj
Fixes #937 
Fixes #935
Allows specifying custom install properties e.g.:
```
PS Z:\Repos\RDMP\Tools\rdmp\bin\Debug\net6.0> ./rdmp install "tcp:myserver.database.windows.net,1433" RDMP_ --createdatabasetimeout 5000 --otherkeywords "Authentication=Active Directory Password;"
```
=> Azure Support

Rdmp.Core/CommandExecution/GoToCommandFactory.cs
=> Fixes #826

Rdmp.UI/ExtractionUIs/FilterUIs/ExtractionFilterUI.Designer.cs
=> Fixes #810

CHANGELOG.md, Rdmp.Core/Curation/Data/SafeDirectoryCatalog.cs, Tests.Common/UnitTests.cs, Tools/rdmp/Program.cs
=> Startup Fixes

CHANGELOG.md, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentCollectionUI.cs
=> Fix pipeline arguments order

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddNewAggregateGraph.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddNewCatalogueItem.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddNewGovernanceDocument.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddNewSupportingDocument.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddNewSupportingSqlTable.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewEmptyCatalogue.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilter.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewGovernancePeriod.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSetExtractionIdentifier.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandViewCatalogueData.cs, Rdmp.Core/Curation/Data/Governance/GovernancePeriod.cs, Rdmp.Core/GlobalStrings.Designer.cs, Rdmp.Core/GlobalStrings.resx, Rdmp.UI.Tests/ArbitraryFolderNodeTests.cs, Rdmp.UI/Collections/CatalogueCollectionUI.cs, Rdmp.UI/Collections/RDMPCollectionCommonFunctionality.cs, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandCheckAsync.cs, Rdmp.UI/Menus/CatalogueFolderMenu.cs, Rdmp.UI/Menus/CatalogueMenu.cs, Rdmp.UI/Menus/RDMPContextMenuStrip.cs
=> Cata menu changes

Rdmp.Core.Tests/Providers/CatalogueProblemProviderTests.cs, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddAggregateConfigurationToCohortIdentificationSetContainer.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddCatalogueToCohortIdentificationAsPatientIndexTable.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddCatalogueToCohortIdentificationSetContainer.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewCohortIdentificationConfiguration.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandImportCohortIdentificationConfiguration.cs, Rdmp.Core/CommandExecution/BasicCommandExecution.cs, Rdmp.Core/Providers/CatalogueProblemProvider.cs, Rdmp.UI/CohortUI/ImportCustomData/CohortCreationRequestUI.Designer.cs, Rdmp.UI/CohortUI/ImportCustomData/CohortCreationRequestUI.cs, Rdmp.UI/Collections/DataExportCollectionUI.cs, Rdmp.UI/CommandExecution/Proposals/ProposeExecutionWhenTargetIsCohortAggregateContainer.cs, Rdmp.UI/Menus/CohortAggregateContainerMenu.cs, Rdmp.UI/Menus/JoinableCollectionNodeMenu.cs, Rdmp.UI/Versioning/CreatePlatformDatabase.cs
=> Updated CohortAggregateContainer errors to be more helpful

Rdmp.Core/Curation/FilterImporting/FilterImportWizard.cs
=> Added null check for adding filter to protect against none being added

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.UI/Menus/CatalogueMenu.cs
=> Right click menu fixes

Rdmp.Core.Tests/DataQualityEngine/CatalogueConstraintReportTests.cs, Rdmp.Core/Curation/KeywordHelp.txt, Rdmp.Core/DataQualityEngine/Data/Evaluation.cs, Rdmp.Core/DataQualityEngine/Reports/CatalogueConstraintReport.cs, Rdmp.Core/Databases/DataQualityEnginePatcher.cs, Rdmp.Core/Databases/PlatformDatabase.cs, Rdmp.Core/Databases/QueryCachingPatcher.cs, Rdmp.Core/Repositories/DQERepository.cs
=> Added table creation logic for DQE database using FAnsiSql notation

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilterFromCatalogue.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSet.cs, Rdmp.Core/Curation/Data/Cohort/AnyTableSqlParameter.cs, Rdmp.Core/Curation/FilterImporting/FilterImportWizard.cs, Rdmp.Core/Providers/DataExportProblemProvider.cs, Rdmp.UI/Menus/FilterMenu.cs, Rdmp.UI/SimpleDialogs/SelectDialog.cs
If an existing filter has params (but no parameter value set) it will prompt the user for values.
Closes #1030 
Closes #1029
Closes #1031
=> Ask filter parameters when adding a filter to CIC

Rdmp.Core/CommandExecution/CommandInvoker.cs
=> Set argument ux

Rdmp.Core.Tests/DataExport/DataExtraction/SimpleFileExtractorTests.cs, Rdmp.Core/DataExport/DataExtraction/Pipeline/FileExtractor.cs, Rdmp.Core/DataExport/DataExtraction/Pipeline/SimpleFileExtractor.cs
Fixes #1050
Fixes #1053
Fixes #1052
=> Simple file extractor fixes

CHANGELOG.md, Rdmp.Core.Tests/CohortCommitting/CreateNewCohortDatabaseWizardTests.cs, Rdmp.Core.Tests/CommandExecution/TestExecuteCommandSetUserSetting.cs, Rdmp.Core.Tests/DataExport/Data/ExtractableCohortTests.cs, Rdmp.Core/DataExport/Data/ExternalCohortTable.cs, Rdmp.Core/DataExport/Data/ExtractableCohort.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.resx, Reusable/ReusableLibraryCode/Checks/ErrorCodes.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Changed AllowIdentifiableExtractions to an error code

Rdmp.Core.Tests/DataLoad/Engine/Integration/PipelineTests/Sources/DelimitedFileSourceTests.cs, Rdmp.Core.Tests/DataLoad/Engine/Integration/PipelineTests/Sources/DelimitedFileSourceTests_Unresolveable.cs, Rdmp.Core/DataLoad/Modules/DataFlowSources/DelimitedFlatFileDataFlowSource.cs
=> Csv quotes

CHANGELOG.md, Rdmp.Core/Curation/Data/Catalogue.cs, Rdmp.Core/Curation/Data/CatalogueItem.cs, Rdmp.Core/Curation/Data/ConcreteFilter.cs, Rdmp.UI/Collections/RDMPCollectionCommonFunctionality.cs, Rdmp.UI/SimpleDialogs/SelectDialog.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Added UsefulProperty columns back into Find/Select dialog

CHANGELOG.md, Rdmp.Core/Curation/Data/Aggregation/AggregateForcedJoin.cs, Rdmp.Core/Repositories/MemoryCatalogueRepository.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Added AlwaysJoinEverything user setting

CHANGELOG.md, Tests.Common/TestDatabases.txt, Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs
=> Added right click context menu support for console gui

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewExtractionConfigurationForProject.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilter.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiRunPipeline.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiTextDialog.cs, Tools/rdmp/CommandLine/Gui/Windows/RunnerWindows/RunEngineWindow.cs
Fixes #1068
Fixes #1077
Fixes #1073
Fixes #1009
=> Pre release tidyup

Application/ResearchDataManagementPlatform/WindowManagement/HomePane/HomeUI.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewCohortIdentificationConfiguration.cs, Rdmp.UI/SimpleControls/SelectIMapsDirectlyToDatabaseTableComboBox.Designer.cs, Rdmp.UI/Wizard/CreateNewCohortIdentificationConfigurationUI.Designer.cs, Rdmp.UI/Wizard/CreateNewCohortIdentificationConfigurationUI.cs, Rdmp.UI/Wizard/SimpleCohortSetUI.Designer.cs, Rdmp.UI/Wizard/SimpleCohortSetUI.cs, Rdmp.UI/Wizard/SimpleFilterUI.Designer.cs, Rdmp.UI/Wizard/SimpleFilterUI.cs, Rdmp.UI/Wizard/SimpleParameterUI.Designer.cs, Rdmp.UI/Wizard/SimpleSetOperation.Designer.cs
=> Fixed layout issues with cohort configuration wizard

CHANGELOG.md, Rdmp.Core.Tests/CommandExecution/ExecuteCommandAddNewFilterContainerTests.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddDimension.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddNewFilterContainer.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilter.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandImportFilterContainerTree.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSetFilterTreeShortcut.cs
=> Drop filter on api is bad

CHANGELOG.md, Rdmp.Core/DataExport/DataExtraction/Pipeline/Sources/ExecuteCrossServerDatasetExtractionSource.cs
=> Fixes #1097

CHANGELOG.md, Rdmp.Core.Tests/CommandExecution/ExecuteCommandRefreshBrokenCohortsTests.cs, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandRefreshBrokenCohorts.cs
=> Added ExecuteCommandRefreshBrokenCohorts

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddAggregateConfigurationToCohortIdentificationSetContainer.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandImportCohortIdentificationConfiguration.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecutecommandAddCohortSubContainer.cs
=> Emphasise aggregate when adding to container

CHANGELOG.md, Rdmp.UI/SubComponents/CohortIdentificationConfigurationUI.Designer.cs
=> Fix cohort builder olvExecute being editable

CHANGELOG.md, Rdmp.Core/DataLoad/Modules/Attachers/RemoteTableAttacher.cs
=> Fixed RemoteTableAttacher not logging the table name it is loading

CHANGELOG.md, Rdmp.UI/PipelineUIs/Pipelines/ConfigureAndExecutePipelineUI.cs, Rdmp.UI/Progress/ProgressUI.Designer.cs, Rdmp.UI/Progress/ProgressUI.cs, Rdmp.UI/Progress/ProgressUI.resx, Rdmp.UI/SimpleControls/CheckAndExecuteUI.cs
=> Added Success/Error bar to Progress UI

CHANGELOG.md, Rdmp.Core.Tests/DataExport/DataExtraction/ExecuteCrossServerDatasetExtractionSourceTest.cs, Rdmp.Core/DataExport/Checks/SelectedDataSetsChecker.cs, Rdmp.Core/DataExport/Data/ExtractableCohort.cs, Rdmp.Core/DataExport/DataExtraction/Pipeline/Sources/ExecuteCrossServerDatasetExtractionSource.cs, Reusable/ReusableLibraryCode/Checks/ErrorCode.cs, Reusable/ReusableLibraryCode/Checks/ErrorCodes.cs
=> Cross server

Rdmp.Core/Providers/CatalogueProblemProvider.cs
=> Fixed bug where API catalogue would expect aggregate dimension

CHANGELOG.md, Rdmp.UI/ChecksUI/ChecksUI.cs, Rdmp.UI/Progress/ProgressUI.Designer.cs, Rdmp.UI/Progress/ProgressUI.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
Added user setting for AutoResizeColumns.
Updated ProgressUI and ChecksUI to use it.
=> Auto resize usersetting

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandChangeExtractionCategory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSimilar.cs, Rdmp.Core/Curation/Data/ColumnInfo.cs, Rdmp.Core/Providers/CatalogueChildProvider.cs, Rdmp.UI/Menus/RDMPContextMenuStrip.cs
Fixes #1145 
- Also improves performance of Similar command which was a big bottleneck.  
- I've added reporting (when enabled) for context menu building so you can see which commands are the slowest to build (e.g. if they are off trying to contact a non existant server etc).
=> Selective refresh

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandAddCohortToExtractionConfiguration.cs
=> Prevent user dragging deprecated cohorts onto ExtractionConfigurations

CHANGELOG.md, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.resx
=> Added find text box to UserSettingsUI

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.Core/CommandExecution/IBasicActivateItems.cs, Tools/rdmp/ColorSettings.yaml, Tools/rdmp/CommandLine/ColorSettings.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiRunPipeline.cs, Tools/rdmp/CommandLine/Gui/Windows/RunnerWindows/RunEngineWindow.cs, Tools/rdmp/rdmp.csproj
=> Message highlighting for RunEngineWindow

CHANGELOG.md, Rdmp.UI/AggregationUIs/AggregateGraphUI.cs, Rdmp.UI/CatalogueSummary/DataQualityReporting/TimePeriodicityChart.cs, Rdmp.UI/CatalogueSummary/LoadEvents/DiffDataTables.cs, Rdmp.UI/CatalogueSummary/LoadEvents/ViewInsertsAndUpdatesDialog.cs, Rdmp.UI/DataLoadUIs/ANOUIs/ANOTableManagement/ColumnInfoToANOTableConverterUI.cs, Rdmp.UI/DataViewing/ViewSQLAndResultsWithDataGridUI.cs, Rdmp.UI/ExtractionUIs/JoinsAndLookups/LookupBrowserUI.cs, Rdmp.UI/Logging/LoggingTabUI.cs, Rdmp.UI/Progress/ProgressUI.cs, Rdmp.UI/ProjectUI/ProjectUI.cs, Rdmp.UI/SimpleDialogs/DataTableViewerUI.cs
=> Set fill weight to 1 for all columns

CHANGELOG.md, Rdmp.UI/ScintillaHelper/ScintillaTextEditorFactory.cs
=> Fixed line numbers being clipped when greater than 99

CHANGELOG.md, Rdmp.UI/DataViewing/ViewSQLAndResultsWithDataGridUI.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Add tracking splitter distances

CHANGELOG.md, Rdmp.Core/Ticketing/PluginTicketingSystem.cs, Rdmp.Core/Ticketing/SimpleTicketingSystem.cs
=> Added SimpleTicketSystem

CHANGELOG.md, Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs, Rdmp.UI/SimpleDialogs/UserSettingsUI.cs, Rdmp.UI/SubComponents/CohortIdentificationConfigurationUI.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Adds user setting ExpandAllInCohortBuilder

CHANGELOG.md, Rdmp.Core/DataExport/DataExtraction/Pipeline/Sources/ExecuteDatasetExtractionSource.cs
=> Fixed OrderByAndDistinctInMemory in batch retry

Rdmp.Core/Curation/FilterImporting/FilterImportWizard.cs
=> Adding a parameter to a filter now shows its initial value

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewCohortIdentificationConfiguration.cs, Rdmp.UI/Wizard/CreateNewCohortIdentificationConfigurationUI.Designer.cs, Rdmp.UI/Wizard/CreateNewCohortIdentificationConfigurationUI.cs
Fixes #1200
Fixes #1199 
Also fixes the create new cohort buttons being "Cancel", "Ok" (i.e. the wrong way around).  Lead with the happy choice
=> Cic tidyup

CHANGELOG.md, Rdmp.Core.Tests/Providers/CatalogueProblemProviderTests.cs, Rdmp.Core/Providers/CatalogueProblemProvider.cs
=> ProblemProvider checks for unquoted dates

Application/ResearchDataManagementPlatform/NLog.template.config, Application/ResearchDataManagementPlatform/ResearchDataManagementPlatform.csproj, CHANGELOG.md, Documentation/CodeTutorials/FAQ.md, Rdmp.UI/ExceptionCounterUI.cs
=> Made NLog logging easier to implement and inclue performance metrics

Application/ResearchDataManagementPlatform/WindowManagement/WindowArranging/WindowArranger.cs, Rdmp.UI/SimpleDialogs/ForwardEngineering/ConfigureCatalogueExtractabilityUI.cs
=> Fixes #1234

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/CatalogueCreationCommands/ExecuteCommandCreateNewCatalogueByImportingFile.cs, Rdmp.Core/DataLoad/Engine/Pipeline/UploadFileUseCase.cs, Rdmp.UI/SimpleDialogs/SimpleFileImporting/CreateNewCatalogueByImportingFileUI.cs, Rdmp.UI/SimpleDialogs/SimpleFileImporting/CreateNewCatalogueByImportingFileUI_Advanced.cs
=> Add IBasicActivateItems as an Initialization object for UploadFileUseCase

Rdmp.UI/SimpleDialogs/SelectDialog.Designer.cs
=> Increased size of loading icon

Rdmp.UI/ScintillaHelper/ScintillaTextEditorFactory.cs
=> Add rethrow that mentions C++ redistributable when Scintilla loading fails

Rdmp.Core.Tests/CommandExecution/TestStartup.cs, Rdmp.Core/Startup/Startup.cs
=> Added null check for MEF property in Startup

CHANGELOG.md, Rdmp.Core/Repositories/Managers/DataExportPropertyManager.cs
=> Fix DataExportPropertyManager Key collision

CHANGELOG.md, Rdmp.UI/ProjectUI/Datasets/ConfigureDatasetUI.Designer.cs, Rdmp.UI/ProjectUI/Datasets/ConfigureDatasetUI.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Add checkbox for show/hide project specific catalogues in ConfigureDatasetUI

Rdmp.Core.Tests/CohortCommitting/CreateNewCohortDatabaseWizardTests.cs, Rdmp.Core/CohortCommitting/CreateNewCohortDatabaseWizard.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiBigListBox.cs
=> Add Exception for specifying varchar(max) etc in cohort wizard

Rdmp.Core/DataExport/Checks/SelectedDataSetsChecker.cs, Reusable/ReusableLibraryCode/Checks/ErrorCodes.cs
=> Changed 'no ExtractionInformation' warning to user configurable level

Rdmp.Core.Tests/Curation/Integration/QueryBuildingTests/AggregateBuilderTests/MySqlAggregateBuilderTests.cs, Rdmp.Core/QueryBuilding/AggregateBuilder.cs
=> Updated graph building engine to prefer use alias in GROUP/ORDER BY for MySql

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs
=> Added 'Set Description' command to AggregateConfiguration context menu

CHANGELOG.md, Rdmp.UI/ProjectUI/ExecuteExtractionUI.cs
=> Removed ExpandAll from ExecuteExtractionUI

CHANGELOG.md, Rdmp.UI.Tests/DesignPatternTests/RunUITests.cs, Rdmp.UI/Collections/RDMPCollectionCommonFunctionality.cs, Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandShowTooltip.cs, Rdmp.UI/Menus/RDMPContextMenuStrip.cs
Fixes #1334
_Popping up a problem_
If there is no problem then the context menu reads:
=> Added ExecuteCommandShowTooltip

Rdmp.Core.Tests/Curation/Integration/LookupTest.cs, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSetExtendedProperty.cs, Rdmp.Core/Curation/Data/ExtendedProperty.cs, Rdmp.Core/Curation/Data/IJoin.cs, Rdmp.Core/Curation/Data/JoinInfo.cs, Rdmp.Core/Curation/Data/Lookup.cs, Rdmp.Core/Curation/DataHelper/JoinHelper.cs
Fixes #1345
Need to fix all 3 of these methods to listen to custom SQL:
=> Support for custom join Sql

.github/workflows/build.yml, Application/ResearchDataManagementPlatform/ResearchDataManagementPlatform.csproj, Rdmp.Core.Tests/Curation/Anonymisation/ANOMigrationTests.cs, Rdmp.Core.Tests/DataLoad/Engine/Integration/ExecuteSqlFileRuntimeTaskTests.cs, Rdmp.Core.Tests/DataLoad/Engine/Integration/WebFileDownloaderTests.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.UI.Tests/TestActivateItems.cs, Tests.Common/Scenarios/TestsRequiringAnExtractionConfiguration.cs
- Minor but they were irritating in the Actions output ...
=> Fix various compiler warnings

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md
Fixes #1357 
Here is a pipeline component if you need to test it:
```csharp
using System;
using System.Data;
using Rdmp.Core.CommandExecution;
using Rdmp.Core.DataFlowPipeline;
using Rdmp.Core.DataFlowPipeline.Requirements;
using ReusableLibraryCode.Checks;
using ReusableLibraryCode.Progress;
namespace Rdmp.Core.DataLoad.Modules.DataFlowOperations
{
class TwentyQuestions : IPluginDataFlowComponent<DataTable>, IPipelineRequirement<IBasicActivateItems>
{
private IBasicActivateItems _activator;
public void Abort(IDataLoadEventListener listener)
{
}
public void Check(ICheckNotifier notifier)
{
}
public void Dispose(IDataLoadEventListener listener, Exception pipelineFailureExceptionIfAny)
{
}
public void PreInitialize(IBasicActivateItems value, IDataLoadEventListener listener)
{
_activator = …
```
=> Made modal input methods on ActivateItems use thread safety 'Invoke'

Rdmp.Core.Tests/Logging/LogManagerTest.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.Core/Databases/LoggingDatabasePatcher.cs, Rdmp.Core/Databases/PlatformDatabase.cs
=> WIP: Started refactor LoggingDatabasePatcher to work cross DBMS

CHANGELOG.md, Rdmp.Core.Tests/Curation/YamlRepositoryTests.cs, Rdmp.Core/Curation/Data/LoadModuleAssembly.cs, Rdmp.Core/Repositories/YamlRepository.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs
=> Fixed YamlRepository serializing plugin zip files as yaml strings

.github/workflows/build.yml, Rdmp.Core.Tests/Curation/Integration/QueryBuildingTests/AggregateBuilderTests/MySqlAggregateBuilderTests.cs, Rdmp.Core.Tests/Logging/DataLoadTaskHelper.cs, Rdmp.Core.Tests/Logging/LogManagerTest.cs, Rdmp.Core/CommandExecution/BasicActivateItems.cs, Rdmp.Core/Curation/Data/Defaults/PermissableDefaultsExtensions.cs, Rdmp.Core/DataQualityEngine/Data/ColumnState.cs, Rdmp.Core/DataQualityEngine/Data/PeriodicityState.cs, Rdmp.Core/DataQualityEngine/Data/RowState.cs, Rdmp.Core/Databases/DataQualityEnginePatcher.cs, Rdmp.Core/Databases/LoggingDatabasePatcher.cs, Rdmp.Core/Databases/QueryCachingPatcher.cs, Rdmp.Core/Logging/DataLoadInfo.cs, Rdmp.Core/Logging/LogManager.cs, Rdmp.Core/Logging/PastEvents/ArchivalDataLoadInfo.cs, Rdmp.Core/Logging/TableLoadInfo.cs, Rdmp.Core/QueryBuilding/AggregateBuilder.cs, Rdmp.Core/Repositories/RowVerCache.cs, Rdmp.UI.Tests/DesignPatternTests/ClassFileEvaluation/DocumentationCrossExaminationTest.cs, Reusable/MapsDirectlyToDatabaseTable/TableRepository.cs, Reusable/MapsDirectlyToDatabaseTable/Versioning/MasterDatabaseScriptExecutor.cs, Reusable/MapsDirectlyToDatabaseTable/Versioning/Patch.cs, Reusable/MapsDirectlyToDatabaseTable/Versioning/Patcher.cs, Reusable/ReusableLibraryCode/Checks/AcceptAllCheckNotifier.cs, Reusable/ReusableLibraryCode/Settings/UserSettings.cs
=> Test creating a MySql logging db from RDMP running on yamlrepository

CHANGELOG.md, Rdmp.Core/DataExport/DataExtraction/Pipeline/Sources/ExecuteDatasetExtractionSource.cs
=> Added ExecuteDatasetExtractionSource.DoNotUseHashJoinsForCatalogues

CHANGELOG.md, Rdmp.UI/CohortUI/ImportCustomData/CohortCreationRequestUI.cs
Fix not showing enough information about why cohort checks failed in CohortCreationRequestUI 
Fixes #1408
=> Show more info in CohortCreationRequestUI

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandDelete.cs, Rdmp.Core/Curation/Data/CommitInProgress.cs
Before this when using a plugin repository you could see:
```
Failed to execute command 'Delete' (Type was 'ExecuteCommandDelete')
There is no ongoing transaction on this Thread, did you try to close the Transaction from another Thread? or did you maybe never start one in the first place?
```
=> Commit system bugs

CHANGELOG.md, Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueArrayUI.cs
Yay for 1 line fixes
Fixes #1420
=> Fixes #1420 Clear object Array of pipeline components

CHANGELOG.md, Rdmp.UI/CohortUI/CohortSourceManagement/ExternalCohortTableUI.cs, Rdmp.UI/SimpleControls/ServerDatabaseTableSelector.Designer.cs, Rdmp.UI/SimpleControls/ServerDatabaseTableSelector.cs
=> Fix not enabling Save on ExternalCohortTableUI on db setting changes

Tools/rdmp/CommandLine/Gui/ConsoleGuiSqlEditor.cs, Tools/rdmp/rdmp.csproj
=> Rollback Terminal.Gui to 1.7.2

Tools/rdmp/Program.cs
=> Fix CLI `--help` showing help twice

Rdmp.Core.Tests/DataExport/Data/ExtractionProgressTests.cs
Fixes #1419
Issue above either never was a problem or was but was since fixed.  This PR is only a unit test that demonstrates behaviour matches expectations
=> Unit test to demonstrate that cloning resets batching

Rdmp.Core.Tests/DataLoad/Engine/Integration/ToMemoryDataLoadJob.cs, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/Curation/Data/DataLoad/LoadMetadata.cs, Rdmp.Core/Curation/Data/ExtendedProperty.cs, Rdmp.Core/DataLoad/Engine/Checks/Checkers/PreExecutionChecker.cs, Rdmp.Core/DataLoad/Engine/Job/DataLoadJob.cs, Rdmp.Core/DataLoad/Engine/Job/IDataLoadJob.cs, Rdmp.Core/DataLoad/Engine/Job/ThrowImmediatelyDataLoadJob.cs, Rdmp.Core/DataLoad/Engine/LoadExecution/Components/PopulateRAW.cs, Rdmp.Core/DataLoad/Engine/LoadProcess/DataLoadProcess.cs
=> Adds `PersistentRaw` extended property to `LoadMetadata`

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/Automation/AutomationCommandExecution.cs
=> Fixes #1468 - Null ref in TUI check/execute when running with YamlRepository

Rdmp.Core/Providers/CatalogueChildProvider.cs, Rdmp.Core/Providers/Nodes/TableInfoDatabaseNode.cs, Rdmp.UI.Tests/ChildProviderTests.cs
=> Fix TableInfoDatabaseNode equality

Rdmp.Core/DataLoad/Modules/Attachers/MDFAttacher.cs
Improve on fix for #1463 (stop assuming all database file paths are Windows-style, since our SQL Servers aren't all running on Windows!)
=> Make DB file locator accept both / and \ as delimiters

.github/workflows/build.yml, Rdmp.Core/Curation/Data/Pipelines/IDataFlowPipelineEngine.cs, Rdmp.Core/DataFlowPipeline/DataFlowPipelineEngine.cs
For the CHI column finder, want to be able to give a single summary UI alert post processing.
This allows for processing alerts to be bundled together and be reported in a non-blocking fashion
=> RDMP-108 Unified UI Alerting from Processing Chunks

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandExportDatabaseToDir.cs
adds ignores for "Rdmp.Core.DataQualityEngine.Data.DQEGraphAnnotation" and "Rdmp.Core.DataQualityEngine.Data.Evaluation" 
adds a try/catch for any future stray issues
=> Add handling for DQE Types

Rdmp.Core/CohortCreation/CohortIdentificationConfigurationUICommon.cs, Rdmp.UI/SubComponents/CohortIdentificationConfigurationUI.cs, Tools/rdmp/CommandLine/Gui/ConsoleGuiCohortIdentificationConfigurationUI.cs
The screenshot shows where the change takes effect. User can now set a timeout value for the cohort builder and it passed correctly.
=> Bug fix/rdmp 135 timeout variable not being passed

CHANGELOG.md, SharedAssemblyInfo.cs, rdmp-client.xml
Updates to prep the 8.1.4 release
=> Prep 8.1.4 Release

Rdmp.Core/DataLoad/Modules/Attachers/ExcelAttacher.cs
Small bug found during final testing prior to release.
excel column offset value was defaulting to null, not 0
=> fix excel attacher bug

CHANGELOG.md, SharedAssemblyInfo.cs, rdmp-client.xml
Bumps version of RDMP.
Will do a final test runthrough today and release on monday …
=> add release date

CHANGELOG.md, Rdmp.Core/Curation/Data/LoadModuleAssembly.cs
Change plugin loading from assumed read/write to just read
-   [x] …
=> Bugfix/rdmp 211: Plugin Read/Write Permissions

directory.build.props
Remove duplicate file - we have two identical files which differ only in case...
=> Delete duplicate directory.build.props

Directory.Packages.props
-   [ ] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPla …
=> bump six sharper

CHANGELOG.md, Rdmp.Core/Repositories/YamlRepository.cs
Proposed fix for #1895 
-   [x] Requested a review by one of the …
=> Fix issue with whitespace confusing encryption key paths

.github/workflows/build.yml
Update  schedules run to match dependabot
-   [x] Other  (if none of the other choices apply)
-   [ ] Requested a …
=> Updatescheduled job

CHANGELOG.md, Rdmp.UI/Wizard/CreateNewDataExtractionProjectUI.cs, SharedAssemblyInfo.cs
Fix issue where project list was null in project creation UI
Tested with customer, and fix was successful …
=> Fix Project Creation UI Issue

.github/workflows/build.yml, CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCloneCohortIdentificationConfiguration.cs, Rdmp.Core/CommandExecution/GoToCommandFactory.cs, Rdmp.UI/LocationsMenu/Versioning/VersioningControlUI.Designer.cs, rdmp-client.xml
Prep RDMP for v8.2.2
-   [ ] Requested a review by one of the …
=> Task/rdmp 229 prep 8.2.2 release

CHANGELOG.md, rdmp-client.xml
Update changelog and set auto-updater location
-   [] Bugfix (non-breaking change which fixes an issue)
-   [ ] Requested a …
=> update release references

Rdmp.Core/DataLoad/Modules/Mutilators/DQEPostLoadRunner.cs
Update DQE Loader to loop through all catalogues, but just the first one
-   [x] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPla …
=> DQE Post Run Loader Catalogue Looping

Documentation/CodeTutorials/Packages.md
Archive.org link occasionally returns a 500, change reference to github package link 
-   [x] Other  (if none of the other choices apply)
-   [ ] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTuto …
=> use non-dead package link

Rdmp.Core.Tests/Rdmp.Core.Tests.csproj, Rdmp.UI.Tests/Rdmp.UI.Tests.csproj, Tests.Common/Tests.Common.csproj
Revert PR #1925 broken by Dependabot issue https://github.com/dependabot/dependabot-core/issues/10459
=> Revert botched Dependabot PR

CHANGELOG.md, SharedAssemblyInfo.cs, rdmp-client.xml
Bump versions for Release
-   [x] Requested a review by one of the …
=> Task/prep 8.3.0

CHANGELOG.md, Rdmp.Core/Providers/CatalogueProblemProvider.cs
Significant Performance Improvement to problem checking during updates
-   [x] Other  (if none of the other choices apply)
-   [x] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPlan. …
=> Performance Improvement

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md
When opening a new tab in RDMP, insert it one to the right of the current active tab if there is one
-   [x] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documen …
=> Smart UI Tabs

CHANGELOG.md, Directory.Packages.props, SharedAssemblyInfo.cs, rdmp-client.xml
Bump version for 8.3.1
-   [ ] Requested a review by one of the …
=> prep 8.3.1 release

Rdmp.Core/Logging/LogManager.cs
Fixes #2030.
It would be good to include tests against postgres in the CI for this, but not sure how much effort that would take.
-   [ ] Have validated this change against the [Test …
=> ensure LogManager commands are quoted for postgres

CHANGELOG.md, Documentation/CodeTutorials/Packages.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandPerformRegexRedactionOnCatalogue.cs, Rdmp.Core/Curation/Data/Overview/OverviewModel.cs, Rdmp.Core/DataLoad/Modules/Mutilators/RegexRedactionMutilator.cs, Rdmp.UI/CommandExecution/Proposals/ProposeExecutionWhenTargetIsCatalogue.cs, SharedAssemblyInfo.cs
Improve speed of Catalogue overview generation
Add missing upstream dependency required from RDMPDicom …
=> Bugfix/rdmp 271 Improve Catalogue Overview Speed

CHANGELOG.md, Rdmp.UI/SimpleDialogs/SelectDialog.cs
Add ability to filter dashboard select
-   [x] Requested a review …
=> Add Filter to Dashboards

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/CohortCreationCommands/CohortCreationCommandExecution.cs
* Improve cohort deprecation replacement text
* When replacing a deprecated cohort usage, ignore frozen ones …
=> update cohort deprecation text

CHANGELOG.md, Rdmp.UI/ApplicationRestarter.cs
There was an issue when restarting that non-main windows would not be closed.
This change fixes that issue …
=> RDMP-277 Fix issue with Restarting not closing all windows

SharedAssemblyInfo.cs
-   [ ] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPla …
=> add rc versioning

.github/workflows/docker.yml, CHANGELOG.md, Rdmp.UI/MainFormUITabs/CatalogueUI.Designer.cs, Rdmp.UI/SimpleDialogs/SelectDialog`1.resx, SharedAssemblyInfo.cs, rdmp-client.xml
Tidy ups ahead of v8.4.3 Release
-   [x] Other  (if none of the other choices apply)
-   [x] Requested a review by one …
=> Task/prep 8.4.3

CHANGELOG.md, SharedAssemblyInfo.cs
Changelog and assembly file updated
-   [ ] Have validated this change against the [Test …
=> Changelog updated

Application/ResearchDataManagementPlatform/Menus/RDMPTopMenuStripUI.cs, Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md, Rdmp.UI/SimpleDialogs/NewfindUI.Designer.cs
* Add contextual search top CTRL+f
*Improve speed of experimental search
-   [x] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPla …
=> RDMP-292 Add contextual Search 

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md
Improve New tab opening to open next to currently focused tab.
Previous solution was flaky on what the active tab was …
=> improve ui tabbing

Application/ResearchDataManagementPlatform/WindowManagement/ActivateItems.cs, CHANGELOG.md, Rdmp.UI/SimpleDialogs/SelectDialog.cs
Fix issue when cancelling out of a multiselect dialog would clear all selected items
Dialog would replace saved value with null when dialog returned non-OK status (i.e. cancel)
-   [x] Have validated this change …
=> Bugfix/rdmp 302 Fix Multiselect Cancel

CHANGELOG.md, SharedAssemblyInfo.cs, rdmp-client.xml
-   [ ] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPla …
=> prep 8.4.4 release

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilter.cs, Rdmp.Core/Curation/Data/ConcreteContainer.cs, Rdmp.Core/Curation/FilterImporting/FilterImportWizard.cs
Allow catalogue cohort filters to be added to extraction configurations
-   [x] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPlan …
=> add ability to use cohort filters at extraction time

CHANGELOG.md, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilter.cs, SharedAssemblyInfo.cs
Fixes issue with orphaned filters causing the UI cohort builder right-click menu
-   [x] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials …
=> Task/fix Cohort Configuration right-click menu not load

Directory.Packages.props, Rdmp.Core/CommandExecution/AtomicCommandFactory.cs, Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilter.cs
Backout change in v9.0.0 that was not required 
-   [ ] Requested …
=> Revert Filter Finder
