HicServices/RDMP

Application/ResearchDataManagementPlatform/WindowManagement/HomePane/HomeBoxUI.cs
CHANGELOG.md
Rdmp.UI/Collections/Providers/HistoryProvider.cs

Fixes an issue in HomeUI where recent items still appeared despite being deleted from the database.  
We could do an exists check up front but it would result in things vanishing and its not how things like word / windows do it so probably best to follow the standard.

Added ability to detect and remove deleted objects from history/recent

---

CHANGELOG.md
Rdmp.Core.Tests/Providers/RowVerTest.cs
Rdmp.Core/Repositories/RowVerCache.cs

Fix for performance improvements when users do not have VIEW CHANGE TRACKING permission

Fixed RowVerCache crashing when user lacks required permissions

---

Application/ResearchDataManagementPlatform/WindowManagement/WindowFactory.cs
Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandShow.cs
Rdmp.UI/ExtractionUIs/ExtractionInformationUI.cs
Rdmp.UI/MainFormUITabs/CatalogueItemUI.cs
Rdmp.UI/Menus/GoToMenuBuilder.cs

This relates to the changelog entry:
```
Fixed bugs in using GoTo menu of document tabs after a Refresh
```
It removes legacy GoTo commands that were part of the 'burger bar' button (in favour of using the right click context menu GoTo):
Also includes rebuilding the `TabPageContextMenuStrip` on every tab after global refreshes (fixes stale GoTo options).

Standardised GoTo and made tab context menu rebuild after refresh

---

Application/ResearchDataManagementPlatform/WindowManagement/WindowManager.cs
CHANGELOG.md
Rdmp.UI/TestsAndSetup/GlobalExceptionHandler.cs
Rdmp.UI/TestsAndSetup/RDMPBootStrapper.cs

Changes how we handle thread and unhandled application exceptions e.g. those caused during rendering and child gettering (see example below).  Previously these were passed to ExceptionViewer (dialog box).  Now this only happens until the main UI is up after which the errors are routed to the task bar error collector button.

Changed domain/thread exceptions to use IActivateItems delegate

---

CHANGELOG.md
Rdmp.Core/DataLoad/Engine/Pipeline/Sources/DbDataCommandDataFlowSource.cs
Rdmp.Core/DataLoad/Modules/Attachers/DelimitedFlatFileAttacher.cs
Rdmp.Core/DataLoad/Modules/Attachers/ExcelAttacher.cs
Rdmp.Core/DataLoad/Modules/Attachers/FixedWidthAttacher.cs
Rdmp.Core/DataLoad/Modules/Attachers/FlatFileAttacher.cs
Rdmp.Core/DataLoad/Modules/Attachers/KVPAttacher.cs
Rdmp.Core/DataLoad/Modules/Attachers/RemoteDatabaseAttacher.cs
Rdmp.Core/DataLoad/Modules/Attachers/RemoteTableAttacher.cs

Better support for abort/cancel in
- RemoteTableAttacher
- ExcelAttacher
- KVPAttacher
- RemoteDatabaseAttacher
This PR changes the signatures of `IterativelyBatchLoadDataIntoDataTable` and `OpenFile` so may require plugin writers to update to latest NuGet package
/fixes #164

Fixed RemoteTableAttacher not honouring cancellation #164

---

Rdmp.Core/DataLoad/Modules/FTP/FTPDownloader.cs
Rdmp.Core/DataLoad/Modules/FTP/SFTPDownloader.cs

/Fixes #336
SFTPDownloader inherits from FTPDownloader.
Previous behaviour:
- FTPDownloader client class has KeepAlive property which defaults to true
- SFTPDownloader has no KeepAlive property only an interval which defaults to -1 (no keep alive).
So I have added a bool property KeepAlive in the base class which defaults to true (keeping original behaviour for FTPDownloader)
And a property KeepAliveIntervalMilliseconds that defaults to 0 which when set to a postive number and combined with KeepAlive will populate the requisite setting in the SFTPDownloader client (preserving previous behaviour of SFTPDownloader)

Added KeepAlive and KeepAliveIntervalMilliseconds

---

CHANGELOG.md
Tools/rdmp/CommandLine/Gui/Windows/RunnerWindows/RunEngineWindow.cs

Fixed RunEngineWindow to look for rdmp binary in correct location

---

CHANGELOG.md
Rdmp.Core/Logging/PastEvents/ArchivalDataLoadInfo.cs
Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs
Rdmp.UI/SimpleDialogs/UserSettingsUI.cs
Reusable/ReusableLibraryCode/Settings/UserSettings.cs

Fixes #424 
You can set this via the UI above or call
```
./rdmp cmd SetUserSetting HideEmptyTableLoadRunAudits  true
```

Added HideEmptyTableLoadRunAudits

---

CHANGELOG.md
Rdmp.Core/CommandLine/Options/ReleaseOptions.cs
Rdmp.Core/CommandLine/Runners/ReleaseRunner.cs

Fixes  #418
If you want to run a release without globals use:
```
release --Configurations 4 --command check --MaxConcurrentExtractions 3 --Pipeline 9 -g false
```

Fixed -g false not working in release CLI args

---

Rdmp.UI/ChecksUI/RAGSmiley.cs

Fixes #430
No changelog entry because this was a side effect of the changes in https://github.com/HicServices/RDMP/pull/400 that has not gone live yet.

Fixed RAGSmiley state sometimes not updating correctly after refactoring

---

CHANGELOG.md
Rdmp.Core.Tests/Reports/CustomMetadataReportTests.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandExtractMetadata.cs
Rdmp.Core/Reports/CustomMetadataReport.cs

- Added custom metadata report tokens:
- $Comma (for use with formats that require seperation e.g. JSON when using the `$foreach` operation)
- $TimeCoverage_ExtractionInformation (the column that provides the time element of a dataset to the DQE e.g. StudyDate)
Closes #495 
Closes #489

Metadata improvements

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFilterFromCatalogue.cs

This PR just removes the behaviour of opening the filter in edit mode when it is imported from Catalogues only.
I don't think we should be 'prompting for parameter values with GetText' like the associated ticket.  Parameter text can be 'T' or 'TODO', how do we know if the parameter value at Catalogue level is already good and only exists for readability or to edit in future.  Better we handle parameter population on creation later on with a specific system.  Either way the user can just double click the new filter to edit it anyway.
Fixes #117

Removed Activate (open) when importing a Catalogue level filter

---

CHANGELOG.md
Rdmp.Core/DataExport/Data/ExternalCohortDefinitionData.cs
Rdmp.Core/DataExport/Data/ExtractableCohort.cs

This static member represents when we cannot get a ExternalCohortDefinitionData from the cohort database for a given OriginID because it was deleted
Fixes #447
_After truncating the CohortDefinition table in the Cohort database_

Added ExternalCohortDefinitionData.Orphan

---

CHANGELOG.md
Rdmp.Core.Tests/DataQualityEngine/PeriodicityStateTests.cs
Rdmp.Core/DataQualityEngine/Data/PeriodicityState.cs
Rdmp.Core/Repositories/DQERepository.cs
Rdmp.Core/Repositories/IDQERepository.cs
Rdmp.UI/CatalogueSummary/DataQualityReporting/TimePeriodicityChart.cs
Rdmp.UI/Raceway/RacewayRenderAreaUI.cs

Fixes #520 
This PR fixes some global errors appearing and general breakdown of the view results UI when the evaluation(s) are of tables that had no rows at the time the DQE was run.
Also included in this PR is the following hot new feature:
Now the message 'Tables were empty' gets shown in the raceway instead of 'No DQE runs'

DQE results behaviour when run on empty tables

---

CHANGELOG.md
Rdmp.Core.Tests/CommandLine/CommandLineObjectPickerTests.cs
Rdmp.Core/CommandLine/Interactive/Picking/CommandLineObjectPicker.cs
Rdmp.Core/CommandLine/Interactive/Picking/PickObjectByQuery.cs

Fixes #521
```
PS Z:\Repos\RDMP\Tools\rdmp\bin\Debug\net5.0> ./rdmp cmd list Catalogue?Folder:*admissions*
2021-09-28 09:17:14.3378 INFO Dotnet Version:5.0.3 .
2021-09-28 09:17:14.3587 INFO RDMP Version:6.0.2.0 .
2021-09-28 09:17:14.5030 INFO Setting yaml config value for CatalogueConnectionString .
2021-09-28 09:17:14.5030 INFO Setting yaml config value for DataExportConnectionString .
4:HospitalAdmissions
5:vConditions
6:vOperations
```

Added support for identifying items by properties on CLI

---

CHANGELOG.md
Rdmp.UI/LocationsMenu/ChoosePlatformDatabasesUI.cs
Rdmp.UI/SimpleControls/ServerDatabaseTableSelector.Designer.cs
Rdmp.UI/SimpleControls/ServerDatabaseTableSelector.cs

Fixes #553 
_New user interface design for failure state.  The cancellation link label is simply reused with its text changed_

Removed RAG smiley from ServerDatabaseTableSelector

---

CHANGELOG.md
Rdmp.UI/Collections/DataExportCollectionUI.cs

Fixed delete many projects/packages at once in DataExportCollectionUI

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewClassBasedProcessTask.cs
Rdmp.Core/CommandExecution/BasicActivateItems.cs
Rdmp.Core/CommandExecution/IBasicActivateItems.cs

API user can still call the overload if they want those to be viable options.
Fixes #659

Fixed interfaces and abstract classes being listed by UI layer method GetType

---

Tools/rdmp/CommandLine/Gui/Windows/RunnerWindows/RunEngineWindow.cs

This fixes an issue where Check/Execute results were not updating in real-time (only when user hit an arrow key etc).
There is still an issue on Linux where arrow keys etc do not update the UI and instead show a console character (see the grey keystrokes in screenshot below) but I think this will be fixed by https://github.com/migueldeicaza/gui.cs/issues/1501 when it goes live.

Fixed Runner execution Process output only refreshing on keystrokes

---

CHANGELOG.md
Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentCollectionUI.cs
Rdmp.UI/SimpleControls/HelpIcon.cs

Fixed stale help when selecting a `PipelineComponent` with no help

---

Rdmp.Core/DataExport/Data/ExtractionConfiguration.cs
Rdmp.UI/ProjectUI/ExecuteExtractionUI.cs
Rdmp.UI/ProjectUI/ExtractionConfigurationUI.cs

Fixes regression in tab titles for extraction projects so that the number is at the start (per user requirements)
closes #621

Changed back tab title so project number is at the start

---

Reusable/ReusableLibraryCode/Settings/RDMPApplicationSettings.cs

Only change in this PR is to put a catch on the method `T GetValueOrDefaultInternal<T>(string key, T defaultValue = default(T), string fileName = null)`.  This means that if the persistence settings store has invalid values e.g. `\0\0` for an int then the default value gets returned
```csharp
}
catch (FormatException)
{
return defaultValue;
}
```

fixed parsing invalid settings to return defaultValue

---

Application/ResearchDataManagementPlatform/Program.cs
Application/ResearchDataManagementPlatform/ResearchDataManagementPlatformOptions.cs
CHANGELOG.md
Plugins/Plugin.UI/Plugin.UI.nuspec
Plugins/Plugin/Plugin.nuspec
Rdmp.Core/CommandLine/Options/RDMPCommandLineOptions.cs
Rdmp.Core/Rdmp.Core.csproj
Tools/rdmp/Program.cs

Fixes #727
Can now specify command line options for the main gui app in a file called `Databases.yaml`:
```
CatalogueConnectionString: Server=(localdb)\MSSQLLocalDB;Database=RDMP_Catalogue;Trusted_Connection=True;
DataExportConnectionString: Server=(localdb)\MSSQLLocalDB;Database=RDMP_DataExport;Trusted_Connection=True;
```
_Databases.yaml_
Can also specify a custom file to load e.g.
```
./ResearchDataManagementPlatform --ConnectionStringsFile ./SHAREDbs.yaml
```

Databasesyaml

---

Rdmp.Core/Curation/Data/DemandsInitializationAttribute.cs
Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentCollectionUI.cs
Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueSqlUI.Designer.cs
Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueSqlUI.cs
Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueUIArgs.cs

Updated ArgumentCollectionUI to support ContextText so a clause (like "WHERE") can be put next to the SQL input box.
For example, adding the collowing ContextText
Could be useful for other controls as well to allow some customisation of the input box from the pipeline component level

Added ContextText to DemandsInitializationAttribute

---

Rdmp.UI.Tests/WideMessageBoxTests.cs
Rdmp.UI/SimpleDialogs/WideMessageBox.Designer.cs
Rdmp.UI/SimpleDialogs/WideMessageBox.cs

Attempting to resolve #747
Line 75 in Rdmp.UI.SimpleDialogs.,WideMessageBox appears to be the root cause of this problem:
`var theScreen = Screen.FromControl(this);`
Since this is only used for sizing the box correctly I've updated the WideMessageBox control layout to be a little more graceful with resizing without having to grab the screen size.
However, the related code (below) does do some useful stuff to stop the window being too big and still being accessible:
`            var theScreen = Screen.FromControl(this);
//enforce sensible max/min sizes
Width = Math.Min(Math.Max(600, Width),theScreen.Bounds.Width - 400);
//if the text is too long vertically just maximise the message box
if (this.Height > theScreen.Bounds.Height)
this.WindowState = FormWindowState.Maximized;`
Not tested yet …

Fixing WideMessageBox grabbing window focus

---

CHANGELOG.md
Rdmp.UI/Rules/BinderRule.cs
Rdmp.UI/Rules/BinderWithErrorProviderFactory.cs
Rdmp.UI/Rules/NoBadNamesRule.cs
Rdmp.UI/Rules/NotNullRule.cs
Rdmp.UI/Rules/UniqueRule.cs

Improves performance of typing in Catalogue Descriptions when there are a lot of Catalogues configured

Fixed BinderRule validating after changed events to unrelated properties

---

Rdmp.UI/AggregationUIs/Advanced/AggregateEditorUI.cs
Rdmp.UI/AggregationUIs/Advanced/AggregateTopXUI.cs
Rdmp.UI/PipelineUIs/DemandsInitializationUIs/ArgumentValueControls/ArgumentValueComboBoxUI.cs
Rdmp.UI/SimpleDialogs/ForwardEngineering/ConfigureCatalogueExtractabilityUI.cs
Rdmp.UI/SimpleDialogs/UserSettingsUI.cs
Rdmp.UI/TestsAndSetup/ServicePropogation/RDMPControlCommonFunctionality.cs

Scroll wheels will not work on comboboxs for AggregateEditorUI, AggregateTopXUI, ArgumentValueComboBoxUI and UserSettingsUI unless the dropdown is expanded.
Closes #778

Added event handlers to stop scroll wheel working on combobox

---

Rdmp.Core/CommandExecution/Combining/CatalogueItemCombineable.cs
Rdmp.UI/Copying/RDMPCombineableFactory.cs

Enables drag and drop operations starting with one or more CatalogueItem objects.  This also enables SQL drag and drop into SQL editors.
Fixes  #835

Added CatalogueItemCombineable

---

CHANGELOG.md
Rdmp.UI/Progress/ProgressUI.Designer.cs
Rdmp.UI/Progress/ProgressUI.cs
Rdmp.UI/SimpleControls/CheckAndExecuteUI.cs

Fixes #888 
Set sender to `ProgressUI.GlobalRunError` in order for the message to always show

Fixed ProgressUI filter to support always showing a given message

---

CHANGELOG.md
Rdmp.UI/CatalogueSummary/LoadEvents/LoadEventsTreeView.cs
Rdmp.UI/Collections/RDMPCollectionCommonFunctionality.cs

Also now has consistent default sort order for first time use
Fixes #902

ViewLogs sort order now persists

---

Rdmp.UI/SimpleDialogs/TaskDescriptionLabel.cs
Rdmp.UI/SimpleDialogs/TypeTextOrCancelDialog.Designer.cs
Rdmp.UI/SimpleDialogs/TypeTextOrCancelDialog.cs

Fixes #911
Fixed for single line:
Also made multiline resize better (it used to only take up a maximum of 240px tall meaning the had a similar problem for much larger descriptions)

Added resizing logic for dialogue box based on the height of the description label

---

CHANGELOG.md
Rdmp.Core.Tests/DataLoad/Engine/Unit/CohortSamplerTests.cs
Rdmp.Core/DataLoad/Modules/DataFlowOperations/CohortSampler.cs

Added CohortSampler

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandChooseCohort.cs

Fixes #1109
_This command and all users of this command (e.g. new ExtractionConfiguration commmand) no longer let you pick deprecated cohorts_

ExecuteCommandChooseCohort no longer lets you pick deprecated cohorts

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommandFactory.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSetAggregateDimension.cs
Rdmp.Core/Providers/CatalogueProblemProvider.cs

Fixes #1102
```
PS Z:\Repos\RDMP\Tools\rdmp\bin\Debug\net6.0> ./rdmp cmd DescribeCommand SetAggregateDimension
Name: ExecuteCommandSetAggregateDimension
Description:
Removes all AggregateDimension on an AggregateConfiguration and creates a single new dimension for linkage in a CohortIdentificationConfiguration based on a chosen ExtractionInformation which must be marked ConcreteColumn.IsExtractionIdentifier
USAGE:
./rdmp.exe cmd SetAggregateDimension <ac> <ei>
PARAMETERS:
ac        AggregateConfiguration The AggregateConfiguration which you want to change the extraction identifier on
ei        ExtractionInformation  The extractable column in the Catalogue which should be created as a new
AggregateDimension on the aggregate.  Or null to prompt at runtime
```

No agg dimension

---

CHANGELOG.md
Rdmp.Core/CohortCreation/Execution/CohortCompilerRunner.cs
Rdmp.Core/QueryBuilding/CohortQueryBuilderResult.cs

Fixes #1131
This is a change to the query building engine so a dangerous area of code to mess with.  But I think this change should achieve the goal.  It makes the CohortCompiler treat set containers as disabled when they are empty.
You can still break it by nesting empty containers but I think that is fine.  
The big run button will also now not run empty containers (when strict validation is disabled).  But the user can manually execute them if they want at which point they will see the Crashed state and an error about the container being empty

Ignore empty cohort containers when strict validation is off

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandConfirmLogs.cs

Adds support for passing 'true' to require that the referenced object (`LoadMetadata:1` in example below) has had rows inserted within the given timeframe as well as the latest load not being a crash.
Fixes  #1139
##Running##
```
PS Z:\Repos\RDMP\Tools\rdmp\bin\Debug\net6.0> .\rdmp.exe cmd ConfirmLogs LoadMetadata:1 null true
2022-05-05 14:00:18.5350 INFO Dotnet Version:6.0.2 .
2022-05-05 14:00:18.5608 INFO RDMP Version:7.0.11.0 .
2022-05-05 14:00:23.8451 ERROR There are no log entries for Capture Algorithm 1232 Results (where rows were loaded) .
```
##Help##
```
PS Z:\Repos\RDMP\Tools\rdmp\bin\Debug\net6.0> .\rdmp.exe cmd DescribeCommand ConfirmLogs
Name: ExecuteCommandConfirmLogs
Description:
Checks the RDMP logs for the latest log entry of a given object. Throws (returns exit code non …
```

Added optional field requireLoadedRows into ExecuteCommandConfirmLogs

---

CHANGELOG.md
Rdmp.UI/SimpleDialogs/ForwardEngineering/ConfigureCatalogueExtractabilityUI.cs

Fixes #1152
This PR adds a new step into the windows client UI for RDMP.  After choosing the 'Add to existing Catalogue' the user is now prompted to pick how to join to the other table(s) in the Catalogue.
The first TableInfo associated with a Catalogue is also marked as 'Is Primary Extraction Table' (at the point when a second table is added).

Added prompts to create JoinInfo when adding new TableInfo to existing Catalogue

---

CHANGELOG.md
Rdmp.Core.Tests/DataLoad/Engine/Integration/ToMemoryDataLoadJob.cs
Rdmp.Core/DataLoad/Engine/Job/DataLoadJob.cs
Rdmp.Core/DataLoad/Engine/Job/IDataLoadJob.cs
Rdmp.Core/DataLoad/Engine/Job/ThrowImmediatelyDataLoadJob.cs
Rdmp.Core/DataLoad/Engine/LoadExecution/SingleJobExecution.cs
Rdmp.Core/DataLoad/Modules/Attachers/FlatFileAttacher.cs

Fixes #1157
For example running a DLE configuration with 2 files in ForLoading only 1 of which is compatible with the loaded table (Biochemistry).  The load results in failure but archiving etc still occurs.

Add IDataLoadJob.CrashAtEnd method

---

CHANGELOG.md
Rdmp.Core.Tests/Curation/Integration/BundledLookupTableTests.cs
Rdmp.Core/DataExport/DataExtraction/ExtractTableVerbatim.cs
Rdmp.Core/DataExport/DataExtraction/Pipeline/Destinations/ExecuteFullExtractionToDatabaseMSSql.cs
Rdmp.Core/DataExport/DataExtraction/Pipeline/Destinations/ExtractionDestination.cs
Rdmp.Core/DataExport/DataExtraction/UserPicks/BundledLookupTable.cs
Rdmp.UI/ExtractionUIs/JoinsAndLookups/KeyDropLocationUI.cs
Tests.Common/UnitTests.cs

Fixes #692
To control what columns are extracted from a Lookup TableInfo.  Create a Catalogue from the TableInfo.  Then change the extractability of the `ExtractionInformation` in the Catalogue. 
- If a Lookup has no Catalogue then all columns are extracted
- If a Lookup has multiple Catalogue then all columns are extracted
- If a Lookup has a single Catalogue but none of the columns are extractable then an Exception is thrown

Lookups now check for a single Catalogue and extract only Core column

---

CHANGELOG.md
Rdmp.UI/SimpleDialogs/SelectDialog.cs

Its not feasible to allow sorting of the find which is already implicitly sorted on 'Sore'.  Performance would be bad and it would be complicated to maintain and error prone (from a usability point of view).
This PR closes #1022 by marking the columns as not sortable.  There is already a fix in for search indicator on another PR.

closes #1022

---

CHANGELOG.md
Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs

Was caused in #1019 by the change of Catalogue.Folder from the type CatalogueFolder to a simple string

Fixed GoTo where path includes CatalogueFolder

---

.github/workflows/build.yml
Rdmp.Core/CommandLine/DatabaseCreation/ExampleDatasetsCreation.cs

This PR fixes the fact that installing on linux or docker etc with the `TrustServerCertificate` setting enabled does not work for example datasets.  This is because there is no `ConnectionStringKeyword` created that would force RDMP to always use that setting when connecting to a DBMS of the sql server type.
This PR updates the install process so that when `TrustServerCertificate` is specified it is created as a permenant rule in the resulting databases.
CI does not bring this issue out because it is using localdb which doesn't require `TrustServerCertificate` of true.

Add -e option to initial install in CI

---

.github/workflows/build.yml
HIC.DataManagementPlatform.sln
Rdmp.Core/CommandLine/Options/ExtractionOptions.cs
Rdmp.Core/CommandLine/RdmpCommandLineBootStrapper.cs
Rdmp.Core/CommandLine/Runners/ExecuteCommandRunner.cs
Tools/rdmp/Program.cs
scripts/create_cohort.yaml
scripts/create_dataload.yaml
scripts/orphan_extractable_column.yaml

fixes #1301
Two fixes in this PR
- Allows running pipelines from RDMP scripts directly e.g.
```
Commands:
- CloneExtractionConfiguration "ExtractionConfiguration:Project 123*2018 Refresh"
- Set ExtractionConfiguration Name "New Clone"
- extract -e "ExtractionConfiguration:New Clone" --command check
- extract -e "ExtractionConfiguration:New Clone" --command run
```
- Digs into #1299 with new CI script orphan_extractable_column.yaml

Orphans and Pipelines

---

CHANGELOG.md
Rdmp.Core/CommandLine/Runners/ReleaseRunner.cs
Rdmp.Core/Icons/IconProvision/StateBasedIconProviders/ExtractableColumnStateBasedIconProvider.cs

This PR has a stealth fix for ReleaseRunner too.  In fact I'm pretty sure that release from CLI is currently broken in release/develop
- Fixes #1316
- Fixes #1312 
Main fix is this:

ExtractableColumn icons and Release engine broken

---

Rdmp.Core/CommandLine/Options/ConnectionStringsYamlFile.cs
Rdmp.Core/Curation/Data/SafeDirectoryCatalog.cs

Seems that when there are dlls where some Types can be resolved but others have dependencies on older versions of RDMP then `Assembly.GetTypes` returns an array with some nulls in it.  There is already code to handle it in RDMP's method `void AddTypes(FileInfo f, Assembly ass, Type[] types, ICheckNotifier listener)`.  But seems that stopped working.  I have fixed the method to properly prune the nulls again.

Fix startup errors with bad plugins

---

CHANGELOG.md
Rdmp.Core/CommandExecution/Combining/AggregateConfigurationCombineable.cs
Rdmp.UI/CommandExecution/Proposals/ProposeExecutionWhenTargetIsSelectedDataSets.cs

Dragging template aggregate to add filters to SelectedDatasets

---

CHANGELOG.md
Rdmp.Core/CommandLine/RdmpCommandLineBootStrapper.cs

Fixes #1346
Running without repo now shows 
> ERROR No repository has been specified.  Either create a Databases.yaml file or provide repository connection strings/paths as command line arguments .
```
PS D:\Repos\RDMP\Tools\rdmp\bin\Debug\net6.0> rm .\Databases.yaml
PS D:\Repos\RDMP\Tools\rdmp\bin\Debug\net6.0> ./rdmp ScriptTables "TableInfo:*smi*table*" MySql smi "./creation.sql"
2022-08-09 09:26:30.4630 INFO Dotnet Version:6.0.7 .
2022-08-09 09:26:30.4812 INFO RDMP Version:7.0.17.0 .
2022-08-09 09:26:30.5954 ERROR No repository has been specified.  Either create a Databases.yaml file or provide repository connection strings/paths as command line arguments .
2022-08-09 09:26:30.5954 INFO Exiting with code 7 .
```

Fix for null RepositoryLocator on CLI

---

CHANGELOG.md
Rdmp.Core/QueryBuilding/SqlQueryBuilderHelper.cs

Use IsExtractionIdentifier column's table if there are 2+ `IsPrimaryExtractionTable` during query building

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandViewLogs.cs

Also better error message when you pass wrong object type e.g. `Project`

Fix ViewLogs not working on CLI gui

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandDescribe.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandSetDefault.cs
Rdmp.Core/Providers/SearchablesMatchScorer.cs

Adds command SetDefault. 
Also contains QoL improvements to CLI.
- Can pass `eds` instead of `ExternalDatabaseServer` e.g. `eds:1`
- When command takes any `Enum` the `describe` now lists the allowed values
```
PS D:\Repos\RDMP\Tools\rdmp> dotnet run -- describe SetDefault -q
Name: ExecuteCommandSetDefault
USAGE:
./rdmp.exe SetDefault <toSet> <server>
PARAMETERS:
toSet          PermissableDefaults    Allowed Values:None, LiveLoggingServer_ID, IdentifierDumpServer_ID, DQE,
WebServiceQueryCachingServer_ID, RAWDataLoadServer, ANOStore,
CohortIdentificationQueryCachingServer_ID
server         ExternalDatabaseServer
The following syntaxes may be used for parameters in this query:
Pick RDMP Object:
Formats:
{Type}:{ID}[,{ID2},{ID3}...]
{Type}:{NamePattern}[,{NamePattern2},{NamePattern3}...] …
```

Add SetDefault command

---

CHANGELOG.md
Rdmp.Core/CommandLine/Options/RDMPCommandLineOptions.cs
Rdmp.Core/Startup/Startup.cs
Rdmp.UI/TestsAndSetup/RDMPBootStrapper.cs
Tools/rdmp/Program.cs

Fixes #1392
To enable use `--skip-patching` flag on windows client (e.g. from a shortcut or .bat file) or CLI client

Add SkipPatching command line option

---

CHANGELOG.md
Rdmp.Core/Curation/Data/EncryptedPasswordHost.cs
Rdmp.Core/Curation/Data/ExternalDatabaseServer.cs
Rdmp.Core/DataLoad/Modules/DataProvider/WebServiceConfiguration.cs
Rdmp.Core/Repositories/MemoryCatalogueRepository.cs
Rdmp.Core/Repositories/YamlRepository.cs

YamlRepository requires to deserialize objects using blank constructor.  That means no access to `IRepository` at that time.  Hence all the blank constructors for objects like `Catalogue`.  Encryption logic is determined by `IRepository`.  To avoid this there was a class added called `FakeEncryptedString`.  But that was never replaced with the real one when it came to `ExternalDatabaseServer`.
Implementation is actually correct for `DataAccessCredentials`  where YamlRepository updates after construction:
```csharp
case DataAccessCredentials creds:
creds.SetEncryptedPasswordHost(new EncryptedPasswordHost(this));
break;
```
This PR does the following
- Add a `throw` when attempting to read a password when `FakeEncryptedString` is installed.  This will prevent the issue going undetected in …

Fixes YamlRepository encryption on ExternalDatabaseServer objects

---

CHANGELOG.md
Tools/rdmp/CommandLine/Gui/ConsoleGuiSqlEditor.cs

Add open button to ConsoleGuiSqlEditor

---

CHANGELOG.md
Rdmp.Core.Tests/Curation/Integration/ServerDefaultsTests.cs
Rdmp.Core/Curation/Data/ExternalDatabaseServer.cs
Rdmp.Core/Repositories/CatalogueRepository.cs
Rdmp.Core/Repositories/MemoryCatalogueRepository.cs
Rdmp.Core/Repositories/YamlRepository.cs
Tests.Common/TestDatabases.txt

Sql Server schema for RDMP has a CASCADE constraint that automatically deletes default declarations when an ExternalDatabaseServer (e.g. logging server) is deleted.
This PR adds a test and a fix for YamlRepository which did not have the same behaviour and left hanging references when deleting

Fix deleting ExternalDatabaseServer with YamlRepository not clearing

---

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewCohortIdentificationConfiguration.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewLoadMetadata.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandPutIntoFolder.cs
Rdmp.UI.Tests/DesignPatternTests/UserInterfaceStandardisationChecker.cs
Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandCreateNewDataExtractionProject.cs
Rdmp.UI/Menus/ProjectFolderMenu.cs
Rdmp.UI/Menus/ProjectMenu.cs

- Right clicking an object and choosing 'put in folder' now pops up showing the current path instead of `\`
- Right clicking a `FolderNode<Project>` now offers you to create a new Project
- Creating a Project, cic or lmd via right click on a folder will create the object in the correct folder (the one right clicked).  Previously would always be created on the root.

Folder fixes

---

Rdmp.Core/Curation/Data/DataAccessCredentials.cs
Rdmp.Core/Curation/Data/EncryptedPasswordHost.cs
Rdmp.Core/Curation/Data/Remoting/RemoteRDMP.cs
Rdmp.Core/DataExport/Data/ExternalCohortTable.cs
Rdmp.Core/Repositories/YamlRepository.cs

#1440 fixed many issues with data access credentials interacting with `YamlRepository`.  But turns out there were other classes that follow the same pattern as those tackled in the previous PR.  This PR applies the same fix pattern to the other object types.  
Also fix to ensure `protected virtual void SetRepositoryOnObject(IMapsDirectlyToDatabaseTable obj)` is called on new objects as well as those loaded from disk by YamlRepository

Apply fixes in  #1440 to other encryption using parts of RDMP

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandViewLogs.cs
Rdmp.Core/CommandLine/Interactive/ConsoleInputManager.cs

Fixes #1447
Changes behaviour of `SelectOne` when `DisallowInput` is true and `AllowAutoSelect` is true (and theres only one object).  In this case the sole value is returned. 
If passed a logging server but no filter then `ViewLogs` will deafult to showing the `DataLoadRun` table.

Fix ViewLogs with eds

---

CHANGELOG.md
Rdmp.UI/Collections/RDMPCollectionCommonFunctionality.cs
Rdmp.UI/Menus/RDMPContextMenuStrip.cs

Prior to this PR the plugin menu items from dicom were not showing, now they are:

Fix passing wrong object to Plugins when right is an empty area of a tree collection

---

Rdmp.Core/DataLoad/Modules/Attachers/MDFAttacher.cs
Rdmp.Core/DataLoad/Modules/Attachers/MdfFileAttachLocations.cs

Finish previous fix - autodetect whether to use Unix or DOS style paths and adjust separator accordingly. Can't rely on Path.Combine - that gets it right for the local machine, not the remote one!

Make file locator handle Unix and DOS style paths more smartly

---

Rdmp.Core/Curation/Data/Catalogue.cs

* Fix apparent regression from PR #1589 in Rdmp.Core/Curation/Data/Catalogue.cs which made it search for "id" instead of "ID", breaking RdmpDicom.

Fix logging server lookup logic

---

Rdmp.UI/SimpleDialogs/ForwardEngineering/ConfigureCatalogueExtractabilityUI.cs

Replace confirmation test of "set x to..." where x is the number of columns to "set a,b and c to ..." where a,b&c are the column names that are going to be set.
maxes out at 3 before "set 4 to..." and for a bulk replace "set all to..."

improve confirmation text

---

Rdmp.Core/Databases/LoggingDatabase/runAfterCreateDatabase/CreateLogging.sql

Fixes a minor typo in the logging server where "Committed" was typo'd as "Commited".
Typo causes problems with key collisions in the logging server.
This fix does not currently modify existing logging servers, only new ones, as comments in the code strongly advise against this

Fix typo in Logging Server Creation Code

---

Rdmp.UI/SimpleDialogs/WideMessageBox.Designer.cs
Rdmp.UI/SimpleDialogs/WideMessageBox.cs

Minor PR to remove sourcecode button in the exception viewer when there is no source class.

Hide source control button when not available during exception show

---

Rdmp.UI/Progress/ProgressUI.cs

When testing the CHI column  finder crashes, it turns out it was the notifications that were causing the spike in resource usage.
From some testing, the actual message gathering and reporting is okay, but the UI updates were not performant.
Have added begin/end data load markers which will stop the UI attempting to re-render while still receiving new data.
Have remove the sorting and it it is again further re-renders for minimal benefit.
Have also removed the auto column resizing as this felt unnecessary given the performance concerns

Task/rdmp-32 Fix Progress Log writing using excessive resources

---

CHANGELOG.md
Rdmp.Core/DataExport/DataExtraction/Pipeline/Sources/ExecuteDatasetExtractionSource.cs
SharedAssemblyInfo.cs

Small update to give the extraction processing chunks names.
This is to be used with some additions to the CHI column finder where it wants to know where the current processing chunk came from.
Also bump to v8.1.1-rc1

Task/rdmp 32 Name DataTable Chunks

---

Rdmp.Core/CommandExecution/AtomicCommandFactory.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewFileBasedProcessTask.cs
Rdmp.Core/Curation/Data/DataLoad/ProcessTask.cs
Rdmp.Core/Curation/Data/DataLoad/ProcessTaskType.cs
Rdmp.Core/DataLoad/Engine/LoadExecution/Components/Runtime/ExecuteSqlBakFileRuntimeTask.cs
Rdmp.Core/DataLoad/Engine/LoadExecution/Components/Runtime/RuntimeTaskFactory.cs
Rdmp.Core/Icons/IconProvision/StateBasedIconProviders/ProcessTaskStateBasedIconProvider.cs
Rdmp.UI/CommandExecution/Proposals/ProposeExecutionWhenTargetIsLoadStageNode.cs
Rdmp.UI/CommandExecution/Proposals/ProposeExecutionWhenTargetIsProcessTask.cs

Allows for .bak files to be mounted into _RAW and used as a data load
N.B. some wrangling of the tables may be required in _Raw/_Staging

RDMP-15 Use .bak files as Data Loads

---

Rdmp.Core/Providers/Nodes/SingletonNode.cs

Revert to previous (technically incorrect) Equals semantics for now, since some UI code was erroneously relying on the incorrect equality test. Should fix properly for the long term (probably checking `.DistinctBy(x=>x.Caption)` instead of plain `.Distinct` in the path calculations).

Restore buggy Equals behaviour on SingletonNode since some UI code relied on it

---

CHANGELOG.md
Documentation/Quickstart.md
README.md
Rdmp.UI.Tests/DesignPatternTests/ClassFileEvaluation/DocumentationCrossExaminationTest.cs

Add some simple quickstart instructions. Has been successfully used by the software team with no issues.

Task/rdmp-79 Quickstart Instructions

---

.github/workflows/build.yml
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandPrunePlugin.cs
Rdmp.Core/CommandLine/Runners/PackPluginRunner.cs
Rdmp.Core/Curation/Data/LoadModuleAssembly.cs
Rdmp.Core/Rdmp.Core.csproj
Rdmp.Core/Startup/Startup.cs
Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandDeletePlugin.cs
SharedAssemblyInfo.cs
rdmp-client.xml

Use rdmpplugins.txt to control plugin loading instead of blindly loading any old nupkg file, workaround for autoupdater leaving old plugin files (and other debris which we should address better at some point!) lying around.
Falls back on previous behaviour (load *.nupkg) if no rdmpplugins.txt file exists.

Plugin loading adjustment (RDMP-130)

---

Rdmp.UI/SimpleDialogs/WideMessageBox.cs

There was an issue where the wide notification form would not be rendered if the user had an alternative focus when RDMP attempted to render the form. Calling focus on the form forces it to be become the focused item within RDMP and be rendered correctly

Task/RDMP-136 Force Wide Form Focus

---

Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs

Fixes #1745
Looks like Terminal.Gui object activation event does fire but possibly the Key.Enter is somehow not marked internal or theres something odd about the way the menu interacts with that bit of the code.
Anyway this workaround is just to switch to the key press event instead.

Fix vanishing menu

---

Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewExternalDatabaseServer.cs

Issue: running the command 
```
/imaging/bin/rdmp/rdmp createnewexternaldatabaseserver None "DatabaseType:MySQL:Server=127.0.0.1;Uid=smi;Pwd=SmiSqlPassword;Database=smi_isolation" --dir /imaging/conf/rdmp
```
Results in the YAML is:
```
Name: New ExternalDatabaseServer 0156c15a-4621-4452-bcbb-1ba87f17c2a9
CreatedByAssembly:
MappedDataPath:
Server:
Database:
Username:
Password:
DatabaseType: MicrosoftSQLServer
ID: 2
```
Running the same command with this updates results in 
```
Name: New ExternalDatabaseServer 208e0a74-93cd-418c-bc81-1a51af53c0cc
CreatedByAssembly: 
MappedDataPath: 
Server: 127.0.0.1
Database: smi_isolation
Username: smi
Password: <Redacted>
DatabaseType: MySql
ID: 3
```

RDMP-149: External Database Command Settings Saved

---

Rdmp.Core/CommandExecution/AtomicCommands/CohortCreationCommands/ExecuteCommandImportAlreadyExistingCohort.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCreateNewExternalDatabaseServer.cs

DLS ran into an issue when trying to import cohort:ID=1 from a remote cohort database when internal cohort:ID=1 already exists.
This fix allows for new cohorts from remote databases to be imported despite the ID clash with internal cohorts by updating the filter to match on ID and source database

Task/RDMP-154 Cohort Importer respects remote server ID

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandMakeCatalogueProjectSpecific.cs

When attempting to convert a catalogue to a project specific catalogue, it is not possible if there are multiple extraction identifiers.
Currently, If you have a project specific catalogue, you can add any number of identifiers.
This is clearly an oversight in the logic check.
Fix allows for catalogue -> project specific conversion as long as there are more than zero identifiers

Allow for multiple identifiers in an project catalogue

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandMakeCatalogueProjectSpecific.cs

When attempting to convert a catalogue to project specific, it would be denied if there was a non-core extraction column.
However, a project specific catalogue could have its column set to any extraction type.
This fix removes the restriction on converting catalogues -> project specific catalogues when they have non-core extraction columns
To Test:
* set a column type to supplementary
* attempt to convert the catalogue to project specific

Task/RDMP-160 Fix Bad Logic Check

---

CHANGELOG.md
Directory.Packages.props
Documentation/CodeTutorials/Packages.md
Rdmp.Core/Rdmp.Core.csproj

There is an issue with the RDMPDicom plugin where it is expecting Microsoft.Bcl.AsyncInterfaces to exist upstream within RDMP.
This stems from the fo-dicom dependency, and is suspected to be because of some .net8 compatibility issue.
Adding the package here resolves this issue, and can be revisited once fo-dicom fully support .net8 without this issue

Task/RDMP-164 Fix Plugin Dependency Issue

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandChangeExtractionCategory.cs
Rdmp.Core/Curation/Data/ExtractionCategory.cs
Rdmp.Core/Icons/IconProvision/StateBasedIconProviders/ExtractionInformationStateBasedIconProvider.cs
SharedAssemblyInfo.cs
directory.build.props

Adds ability to mark Catalogue column as not extractable.
Functionality already exists, but is a bit circuitous as it required deleting the ExtractionCategory within the Catalogue Column
This update adds the "Not Extractable" ExtractionCategory type, which under the hood just nullifies the ExtractionCategory . This provides the same functionality as the existing method, but with a nicer user experience
As we are actually deleting the ExtractionCategory under the hood, we don't need to worry about these items appearing in extraction configurations
To Test:
Set the extraction category of a catalogue column to "Not extractable"
It will appear in a "Non extractable" folder within the catalogue

Task/RDMP-161 Add ability to mark as not extractable

---

CHANGELOG.md
Rdmp.Core/DataExport/Checks/SelectedDataSetsChecker.cs
Rdmp.UI.Tests/UITimeoutAttribute.cs
Rdmp.UI/RichTextBoxEx.cs
Rdmp.UI/SimpleDialogs/ConfigurePrimaryKeyCollisionResolverUI.cs
Rdmp.UI/TransparentHelpSystem/TransparentHelpForm.cs
directory.build.props

DLS came across an issue with a useful error message being swallowed by RDMP.
Fix allows the real error message to be seen and fixes a winforms user32.dll import issue
To Test:
- see James as It's fiddly

Bugfix/rdmp 162 Fix Error Msg Being Swallowed

---

.github/pull_request_template.md
Documentation/CodeTutorials/TestPlan.md

-   [ ] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/task/document-test-plan/Documentation/CodeT …

update test plan

---

CHANGELOG.md
Directory.Packages.props
Rdmp.Core/DataLoad/Modules/FTP/FTPDownloader.cs
Rdmp.Core/DataLoad/Modules/FTP/SFTPDownloader.cs

Keepalive and connectedness check for FTP and SFTP fetch jobs.
- …

FTP, SFTP timeouts and liveness checks

---

.github/workflows/build.yml
Rdmp.Core.Tests/DataLoad/Engine/Integration/RemoteDatabaseAttacherTests.cs
Rdmp.Core.Tests/DataLoad/Modules/Attachers/RemoteTableAttacherTests.cs

attempted fix for 2am run issues.
Adds a nightly cron for 1am UTC
-   [X] Bugfix (non-breaking change which fixes an issue)
-   [X] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
-   [X] Created or updated any tests if relevant
-   [X] Have validated this change against the [Test Plan](https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/TestPlan.md) …

Bugfix/RDMP-188 Attempt fix for 2am UTC issue

---

Rdmp.UI/LocationsMenu/Versioning/VersioningControlUI.Designer.cs

Make Cohort version dropdown options long enough to fit the option names
Dynamically figures out the correct length required to display the full text …

Make Cohort Version Dropdown Options Longer

---

CHANGELOG.md
Rdmp.Core.Tests/CohortCreation/CohortVersioningTests.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandRevertToHistoricalCohortVersion.cs
Rdmp.Core/Curation/Data/Cohort/CohortIdentificationConfiguration.cs
Rdmp.UI/LocationsMenu/Versioning/VersioningControlUI.Designer.cs

Add ability to use cohort version as new root cohort.
Replaced cohort config with clone of historical version …

RDMP-218 Use Historical Cohort Version

---

CHANGELOG.md
Rdmp.Core/Repositories/YamlRepository.cs

Issue raised :https://github.com/HicServices/RDMP/issues/1907
YAML repo was not population the encryption key before trying to decrypt the passwords.
Reordering the object load resolves this issue
-   [x] Have …

RDMP-228 Reorder YAML Data Load

---

CHANGELOG.md
Directory.Packages.props
Rdmp.Core/DataLoad/Modules/FTP/FTPDownloader.cs
Rdmp.Core/DataLoad/Modules/FTP/SFTPDownloader.cs
SharedAssemblyInfo.cs

Fix issue with SFTP timeout not being respected.
DLS has issue post-upgrade with SFTP timing out.
Fix adds SFTP specific checks, rather than using FTP checks and uses the overrides for connection timeouts as defined by the user
-   [x] Created or updated any tests …

Fix SFTP Timeout Issue

---

Application/ResearchDataManagementPlatform/WindowManagement/CollectionNavigation.cs
Documentation/CodeTutorials/Packages.md
Rdmp.Core/Rdmp.Core.csproj

We were importing the entire `Equ` Nuget package just to implement the `.Equals()` method for a single class, which seems a little inefficient...
-   [ ] Have validated this change against the [Test …

Remove trivial Equ usage

---

Tests.Common/TestDatabases.txt

Currently CI wastes c 2s per unit test trying to connect to a PostgreSQL server we don't have in CI - commenting out that line cuts about 90s off each test run or 3m of Github hosted runner usage.
-   [ ] Have …

Remove credentials for Postgres test server we do not have

---

CHANGELOG.md
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandPerformRegexRedactionOnCatalogue.cs
Rdmp.Core/DataLoad/Modules/Mutilators/RegexRedactionMutilator.cs

set release date and make regex like case sensitive
-   [ ] …

update changelog and make like case sensitive

---

Rdmp.Core.Tests/CommandExecution/ExecuteCommandUpdateCatalogueDataLocationTests.cs
Rdmp.Core.Tests/DataExport/DataExtraction/ExecuteFullExtractionToDatabaseMSSqlDestinationReExtractionTest.cs
Rdmp.Core.Tests/DataLoad/Engine/Integration/DataTableUploadDestinationTests.cs
Rdmp.Core.Tests/DataLoad/Engine/Integration/PipelineTests/Sources/DelimitedFileSourceTests_ResolvedAccordingToStrategy.cs
Rdmp.Core.Tests/DataLoad/Engine/Integration/PipelineTests/Sources/DelimitedFileSourceTests_Unresolveable.cs
Rdmp.Core/CommandExecution/AtomicCommands/CohortCreationCommands/ExecuteCommandCreateNewCohortByExecutingACohortIdentificationConfiguration.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandCloneExtractionConfiguration.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandDeprecate.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandRevertToHistoricalCohortVersion.cs
Rdmp.Core/CommandExecution/AtomicCommands/ExecuteCommandUpdateCatalogueDataLocation.cs
Rdmp.Core/Curation/Data/Catalogue.cs
Rdmp.Core/Curation/Data/Overview/OverviewModel.cs
Rdmp.Core/DataExport/DataExtraction/Pipeline/Sources/ExecuteDatasetExtractionSource.cs
Rdmp.Core/DataLoad/Engine/Job/JobFactory.cs
Rdmp.Core/DataLoad/Engine/Job/Scheduling/SingleScheduledJobFactory.cs
Rdmp.Core/DataLoad/Engine/Pipeline/Destinations/DataTableUploadDestination.cs
Rdmp.Core/DataLoad/Modules/Mutilators/RegexRedactionMutilator.cs
Rdmp.UI/CommandExecution/AtomicCommands/ExecuteCommandReorderFilter.cs
Rdmp.UI/ExtractionUIs/JoinsAndLookups/LookupConfigurationUI.cs
Rdmp.UI/LoadExecutionUIs/ExecuteLoadMetadataUI.cs
Rdmp.UI/SimpleDialogs/InstanceSettings.cs
Rdmp.UI/SimpleDialogs/NewfindUI.cs
Rdmp.UI/Wizard/CreateNewDataExtractionProjectUI.cs
Tests.Common/UnitTests.cs

Fix up some .Dispose/using issues, make finding most recent load ID more efficient
- Fix up some missed `using` opportunities and duplicate `.Dispose()` calls, also inefficient LINQ invocations
-   [ ] Have …

Fix up some codeql/inspection code issues

---

CHANGELOG.md
Rdmp.Core/DataExport/DataExtraction/Pipeline/SimpleFileExtractor.cs

There is an issue with the checking stage of the SimpleFileExtractor where it it trying to check an uninitialized variable.
This fix removes this from the checks, as the variable isn't set till runtime
-   [X] Bugfix (non-breaking change which fixes an issue)
-   [X] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
-   [X] Created or updated any tests if relevant
-   [X] Have …

fix simple file extractor check error
